// Code generated by ent, DO NOT EDIT.

package change

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/farmtable-io/farmtable/internal/store/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Change {
	return predicate.Change(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Change {
	return predicate.Change(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Change {
	return predicate.Change(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Change {
	return predicate.Change(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Change {
	return predicate.Change(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Change {
	return predicate.Change(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Change {
	return predicate.Change(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Change {
	return predicate.Change(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Change {
	return predicate.Change(sql.FieldLTE(FieldID, id))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v uuid.UUID) predicate.Change {
	return predicate.Change(sql.FieldEQ(FieldTaskID, v))
}

// AuthorID applies equality check predicate on the "author_id" field. It's identical to AuthorIDEQ.
func AuthorID(v uuid.UUID) predicate.Change {
	return predicate.Change(sql.FieldEQ(FieldAuthorID, v))
}

// FieldName applies equality check predicate on the "field_name" field. It's identical to FieldNameEQ.
func FieldName(v string) predicate.Change {
	return predicate.Change(sql.FieldEQ(FieldFieldName, v))
}

// OldValue applies equality check predicate on the "old_value" field. It's identical to OldValueEQ.
func OldValue(v string) predicate.Change {
	return predicate.Change(sql.FieldEQ(FieldOldValue, v))
}

// NewValue applies equality check predicate on the "new_value" field. It's identical to NewValueEQ.
func NewValue(v string) predicate.Change {
	return predicate.Change(sql.FieldEQ(FieldNewValue, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Change {
	return predicate.Change(sql.FieldEQ(FieldCreatedAt, v))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v uuid.UUID) predicate.Change {
	return predicate.Change(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v uuid.UUID) predicate.Change {
	return predicate.Change(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...uuid.UUID) predicate.Change {
	return predicate.Change(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...uuid.UUID) predicate.Change {
	return predicate.Change(sql.FieldNotIn(FieldTaskID, vs...))
}

// AuthorIDEQ applies the EQ predicate on the "author_id" field.
func AuthorIDEQ(v uuid.UUID) predicate.Change {
	return predicate.Change(sql.FieldEQ(FieldAuthorID, v))
}

// AuthorIDNEQ applies the NEQ predicate on the "author_id" field.
func AuthorIDNEQ(v uuid.UUID) predicate.Change {
	return predicate.Change(sql.FieldNEQ(FieldAuthorID, v))
}

// AuthorIDIn applies the In predicate on the "author_id" field.
func AuthorIDIn(vs ...uuid.UUID) predicate.Change {
	return predicate.Change(sql.FieldIn(FieldAuthorID, vs...))
}

// AuthorIDNotIn applies the NotIn predicate on the "author_id" field.
func AuthorIDNotIn(vs ...uuid.UUID) predicate.Change {
	return predicate.Change(sql.FieldNotIn(FieldAuthorID, vs...))
}

// AuthorIDGT applies the GT predicate on the "author_id" field.
func AuthorIDGT(v uuid.UUID) predicate.Change {
	return predicate.Change(sql.FieldGT(FieldAuthorID, v))
}

// AuthorIDGTE applies the GTE predicate on the "author_id" field.
func AuthorIDGTE(v uuid.UUID) predicate.Change {
	return predicate.Change(sql.FieldGTE(FieldAuthorID, v))
}

// AuthorIDLT applies the LT predicate on the "author_id" field.
func AuthorIDLT(v uuid.UUID) predicate.Change {
	return predicate.Change(sql.FieldLT(FieldAuthorID, v))
}

// AuthorIDLTE applies the LTE predicate on the "author_id" field.
func AuthorIDLTE(v uuid.UUID) predicate.Change {
	return predicate.Change(sql.FieldLTE(FieldAuthorID, v))
}

// FieldNameEQ applies the EQ predicate on the "field_name" field.
func FieldNameEQ(v string) predicate.Change {
	return predicate.Change(sql.FieldEQ(FieldFieldName, v))
}

// FieldNameNEQ applies the NEQ predicate on the "field_name" field.
func FieldNameNEQ(v string) predicate.Change {
	return predicate.Change(sql.FieldNEQ(FieldFieldName, v))
}

// FieldNameIn applies the In predicate on the "field_name" field.
func FieldNameIn(vs ...string) predicate.Change {
	return predicate.Change(sql.FieldIn(FieldFieldName, vs...))
}

// FieldNameNotIn applies the NotIn predicate on the "field_name" field.
func FieldNameNotIn(vs ...string) predicate.Change {
	return predicate.Change(sql.FieldNotIn(FieldFieldName, vs...))
}

// FieldNameGT applies the GT predicate on the "field_name" field.
func FieldNameGT(v string) predicate.Change {
	return predicate.Change(sql.FieldGT(FieldFieldName, v))
}

// FieldNameGTE applies the GTE predicate on the "field_name" field.
func FieldNameGTE(v string) predicate.Change {
	return predicate.Change(sql.FieldGTE(FieldFieldName, v))
}

// FieldNameLT applies the LT predicate on the "field_name" field.
func FieldNameLT(v string) predicate.Change {
	return predicate.Change(sql.FieldLT(FieldFieldName, v))
}

// FieldNameLTE applies the LTE predicate on the "field_name" field.
func FieldNameLTE(v string) predicate.Change {
	return predicate.Change(sql.FieldLTE(FieldFieldName, v))
}

// FieldNameContains applies the Contains predicate on the "field_name" field.
func FieldNameContains(v string) predicate.Change {
	return predicate.Change(sql.FieldContains(FieldFieldName, v))
}

// FieldNameHasPrefix applies the HasPrefix predicate on the "field_name" field.
func FieldNameHasPrefix(v string) predicate.Change {
	return predicate.Change(sql.FieldHasPrefix(FieldFieldName, v))
}

// FieldNameHasSuffix applies the HasSuffix predicate on the "field_name" field.
func FieldNameHasSuffix(v string) predicate.Change {
	return predicate.Change(sql.FieldHasSuffix(FieldFieldName, v))
}

// FieldNameEqualFold applies the EqualFold predicate on the "field_name" field.
func FieldNameEqualFold(v string) predicate.Change {
	return predicate.Change(sql.FieldEqualFold(FieldFieldName, v))
}

// FieldNameContainsFold applies the ContainsFold predicate on the "field_name" field.
func FieldNameContainsFold(v string) predicate.Change {
	return predicate.Change(sql.FieldContainsFold(FieldFieldName, v))
}

// OldValueEQ applies the EQ predicate on the "old_value" field.
func OldValueEQ(v string) predicate.Change {
	return predicate.Change(sql.FieldEQ(FieldOldValue, v))
}

// OldValueNEQ applies the NEQ predicate on the "old_value" field.
func OldValueNEQ(v string) predicate.Change {
	return predicate.Change(sql.FieldNEQ(FieldOldValue, v))
}

// OldValueIn applies the In predicate on the "old_value" field.
func OldValueIn(vs ...string) predicate.Change {
	return predicate.Change(sql.FieldIn(FieldOldValue, vs...))
}

// OldValueNotIn applies the NotIn predicate on the "old_value" field.
func OldValueNotIn(vs ...string) predicate.Change {
	return predicate.Change(sql.FieldNotIn(FieldOldValue, vs...))
}

// OldValueGT applies the GT predicate on the "old_value" field.
func OldValueGT(v string) predicate.Change {
	return predicate.Change(sql.FieldGT(FieldOldValue, v))
}

// OldValueGTE applies the GTE predicate on the "old_value" field.
func OldValueGTE(v string) predicate.Change {
	return predicate.Change(sql.FieldGTE(FieldOldValue, v))
}

// OldValueLT applies the LT predicate on the "old_value" field.
func OldValueLT(v string) predicate.Change {
	return predicate.Change(sql.FieldLT(FieldOldValue, v))
}

// OldValueLTE applies the LTE predicate on the "old_value" field.
func OldValueLTE(v string) predicate.Change {
	return predicate.Change(sql.FieldLTE(FieldOldValue, v))
}

// OldValueContains applies the Contains predicate on the "old_value" field.
func OldValueContains(v string) predicate.Change {
	return predicate.Change(sql.FieldContains(FieldOldValue, v))
}

// OldValueHasPrefix applies the HasPrefix predicate on the "old_value" field.
func OldValueHasPrefix(v string) predicate.Change {
	return predicate.Change(sql.FieldHasPrefix(FieldOldValue, v))
}

// OldValueHasSuffix applies the HasSuffix predicate on the "old_value" field.
func OldValueHasSuffix(v string) predicate.Change {
	return predicate.Change(sql.FieldHasSuffix(FieldOldValue, v))
}

// OldValueIsNil applies the IsNil predicate on the "old_value" field.
func OldValueIsNil() predicate.Change {
	return predicate.Change(sql.FieldIsNull(FieldOldValue))
}

// OldValueNotNil applies the NotNil predicate on the "old_value" field.
func OldValueNotNil() predicate.Change {
	return predicate.Change(sql.FieldNotNull(FieldOldValue))
}

// OldValueEqualFold applies the EqualFold predicate on the "old_value" field.
func OldValueEqualFold(v string) predicate.Change {
	return predicate.Change(sql.FieldEqualFold(FieldOldValue, v))
}

// OldValueContainsFold applies the ContainsFold predicate on the "old_value" field.
func OldValueContainsFold(v string) predicate.Change {
	return predicate.Change(sql.FieldContainsFold(FieldOldValue, v))
}

// NewValueEQ applies the EQ predicate on the "new_value" field.
func NewValueEQ(v string) predicate.Change {
	return predicate.Change(sql.FieldEQ(FieldNewValue, v))
}

// NewValueNEQ applies the NEQ predicate on the "new_value" field.
func NewValueNEQ(v string) predicate.Change {
	return predicate.Change(sql.FieldNEQ(FieldNewValue, v))
}

// NewValueIn applies the In predicate on the "new_value" field.
func NewValueIn(vs ...string) predicate.Change {
	return predicate.Change(sql.FieldIn(FieldNewValue, vs...))
}

// NewValueNotIn applies the NotIn predicate on the "new_value" field.
func NewValueNotIn(vs ...string) predicate.Change {
	return predicate.Change(sql.FieldNotIn(FieldNewValue, vs...))
}

// NewValueGT applies the GT predicate on the "new_value" field.
func NewValueGT(v string) predicate.Change {
	return predicate.Change(sql.FieldGT(FieldNewValue, v))
}

// NewValueGTE applies the GTE predicate on the "new_value" field.
func NewValueGTE(v string) predicate.Change {
	return predicate.Change(sql.FieldGTE(FieldNewValue, v))
}

// NewValueLT applies the LT predicate on the "new_value" field.
func NewValueLT(v string) predicate.Change {
	return predicate.Change(sql.FieldLT(FieldNewValue, v))
}

// NewValueLTE applies the LTE predicate on the "new_value" field.
func NewValueLTE(v string) predicate.Change {
	return predicate.Change(sql.FieldLTE(FieldNewValue, v))
}

// NewValueContains applies the Contains predicate on the "new_value" field.
func NewValueContains(v string) predicate.Change {
	return predicate.Change(sql.FieldContains(FieldNewValue, v))
}

// NewValueHasPrefix applies the HasPrefix predicate on the "new_value" field.
func NewValueHasPrefix(v string) predicate.Change {
	return predicate.Change(sql.FieldHasPrefix(FieldNewValue, v))
}

// NewValueHasSuffix applies the HasSuffix predicate on the "new_value" field.
func NewValueHasSuffix(v string) predicate.Change {
	return predicate.Change(sql.FieldHasSuffix(FieldNewValue, v))
}

// NewValueIsNil applies the IsNil predicate on the "new_value" field.
func NewValueIsNil() predicate.Change {
	return predicate.Change(sql.FieldIsNull(FieldNewValue))
}

// NewValueNotNil applies the NotNil predicate on the "new_value" field.
func NewValueNotNil() predicate.Change {
	return predicate.Change(sql.FieldNotNull(FieldNewValue))
}

// NewValueEqualFold applies the EqualFold predicate on the "new_value" field.
func NewValueEqualFold(v string) predicate.Change {
	return predicate.Change(sql.FieldEqualFold(FieldNewValue, v))
}

// NewValueContainsFold applies the ContainsFold predicate on the "new_value" field.
func NewValueContainsFold(v string) predicate.Change {
	return predicate.Change(sql.FieldContainsFold(FieldNewValue, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Change {
	return predicate.Change(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Change {
	return predicate.Change(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Change {
	return predicate.Change(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Change {
	return predicate.Change(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Change {
	return predicate.Change(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Change {
	return predicate.Change(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Change {
	return predicate.Change(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Change {
	return predicate.Change(sql.FieldLTE(FieldCreatedAt, v))
}

// HasTask applies the HasEdge predicate on the "task" edge.
func HasTask() predicate.Change {
	return predicate.Change(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TaskTable, TaskColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaskWith applies the HasEdge predicate on the "task" edge with a given conditions (other predicates).
func HasTaskWith(preds ...predicate.Task) predicate.Change {
	return predicate.Change(func(s *sql.Selector) {
		step := newTaskStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Change) predicate.Change {
	return predicate.Change(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Change) predicate.Change {
	return predicate.Change(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Change) predicate.Change {
	return predicate.Change(sql.NotPredicates(p))
}
