// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/farmtable-io/farmtable/internal/store/ent/change"
	"github.com/farmtable-io/farmtable/internal/store/ent/task"
	"github.com/google/uuid"
)

// Change is the model entity for the Change schema.
type Change struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID uuid.UUID `json:"task_id,omitempty"`
	// AuthorID holds the value of the "author_id" field.
	AuthorID uuid.UUID `json:"author_id,omitempty"`
	// FieldName holds the value of the "field_name" field.
	FieldName string `json:"field_name,omitempty"`
	// OldValue holds the value of the "old_value" field.
	OldValue string `json:"old_value,omitempty"`
	// NewValue holds the value of the "new_value" field.
	NewValue string `json:"new_value,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChangeQuery when eager-loading is set.
	Edges        ChangeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChangeEdges holds the relations/edges for other nodes in the graph.
type ChangeEdges struct {
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChangeEdges) TaskOrErr() (*Task, error) {
	if e.Task != nil {
		return e.Task, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "task"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Change) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case change.FieldFieldName, change.FieldOldValue, change.FieldNewValue:
			values[i] = new(sql.NullString)
		case change.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case change.FieldID, change.FieldTaskID, change.FieldAuthorID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Change fields.
func (_m *Change) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case change.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case change.FieldTaskID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value != nil {
				_m.TaskID = *value
			}
		case change.FieldAuthorID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field author_id", values[i])
			} else if value != nil {
				_m.AuthorID = *value
			}
		case change.FieldFieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field field_name", values[i])
			} else if value.Valid {
				_m.FieldName = value.String
			}
		case change.FieldOldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field old_value", values[i])
			} else if value.Valid {
				_m.OldValue = value.String
			}
		case change.FieldNewValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field new_value", values[i])
			} else if value.Valid {
				_m.NewValue = value.String
			}
		case change.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Change.
// This includes values selected through modifiers, order, etc.
func (_m *Change) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTask queries the "task" edge of the Change entity.
func (_m *Change) QueryTask() *TaskQuery {
	return NewChangeClient(_m.config).QueryTask(_m)
}

// Update returns a builder for updating this Change.
// Note that you need to call Change.Unwrap() before calling this method if this Change
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Change) Update() *ChangeUpdateOne {
	return NewChangeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Change entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Change) Unwrap() *Change {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Change is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Change) String() string {
	var builder strings.Builder
	builder.WriteString("Change(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("task_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaskID))
	builder.WriteString(", ")
	builder.WriteString("author_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuthorID))
	builder.WriteString(", ")
	builder.WriteString("field_name=")
	builder.WriteString(_m.FieldName)
	builder.WriteString(", ")
	builder.WriteString("old_value=")
	builder.WriteString(_m.OldValue)
	builder.WriteString(", ")
	builder.WriteString("new_value=")
	builder.WriteString(_m.NewValue)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Changes is a parsable slice of Change.
type Changes []*Change
