// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ApiToken is the predicate function for apitoken builders.
type ApiToken func(*sql.Selector)

// Change is the predicate function for change builders.
type Change func(*sql.Selector)

// Collection is the predicate function for collection builders.
type Collection func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Relationship is the predicate function for relationship builders.
type Relationship func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
