// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/farmtable-io/farmtable/internal/store/ent/collection"
	"github.com/farmtable-io/farmtable/internal/store/ent/predicate"
	"github.com/farmtable-io/farmtable/internal/store/ent/task"
	"github.com/google/uuid"
)

// CollectionUpdate is the builder for updating Collection entities.
type CollectionUpdate struct {
	config
	hooks    []Hook
	mutation *CollectionMutation
}

// Where appends a list predicates to the CollectionUpdate builder.
func (_u *CollectionUpdate) Where(ps ...predicate.Collection) *CollectionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *CollectionUpdate) SetName(v string) *CollectionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CollectionUpdate) SetNillableName(v *string) *CollectionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CollectionUpdate) SetDescription(v string) *CollectionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CollectionUpdate) SetNillableDescription(v *string) *CollectionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *CollectionUpdate) ClearDescription() *CollectionUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *CollectionUpdate) SetPlatform(v collection.Platform) *CollectionUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *CollectionUpdate) SetNillablePlatform(v *collection.Platform) *CollectionUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetRemoteID sets the "remote_id" field.
func (_u *CollectionUpdate) SetRemoteID(v string) *CollectionUpdate {
	_u.mutation.SetRemoteID(v)
	return _u
}

// SetNillableRemoteID sets the "remote_id" field if the given value is not nil.
func (_u *CollectionUpdate) SetNillableRemoteID(v *string) *CollectionUpdate {
	if v != nil {
		_u.SetRemoteID(*v)
	}
	return _u
}

// ClearRemoteID clears the value of the "remote_id" field.
func (_u *CollectionUpdate) ClearRemoteID() *CollectionUpdate {
	_u.mutation.ClearRemoteID()
	return _u
}

// SetRemoteData sets the "remote_data" field.
func (_u *CollectionUpdate) SetRemoteData(v map[string]interface{}) *CollectionUpdate {
	_u.mutation.SetRemoteData(v)
	return _u
}

// ClearRemoteData clears the value of the "remote_data" field.
func (_u *CollectionUpdate) ClearRemoteData() *CollectionUpdate {
	_u.mutation.ClearRemoteData()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CollectionUpdate) SetUpdatedAt(v time.Time) *CollectionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (_u *CollectionUpdate) AddTaskIDs(ids ...uuid.UUID) *CollectionUpdate {
	_u.mutation.AddTaskIDs(ids...)
	return _u
}

// AddTasks adds the "tasks" edges to the Task entity.
func (_u *CollectionUpdate) AddTasks(v ...*Task) *CollectionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskIDs(ids...)
}

// Mutation returns the CollectionMutation object of the builder.
func (_u *CollectionUpdate) Mutation() *CollectionMutation {
	return _u.mutation
}

// ClearTasks clears all "tasks" edges to the Task entity.
func (_u *CollectionUpdate) ClearTasks() *CollectionUpdate {
	_u.mutation.ClearTasks()
	return _u
}

// RemoveTaskIDs removes the "tasks" edge to Task entities by IDs.
func (_u *CollectionUpdate) RemoveTaskIDs(ids ...uuid.UUID) *CollectionUpdate {
	_u.mutation.RemoveTaskIDs(ids...)
	return _u
}

// RemoveTasks removes "tasks" edges to Task entities.
func (_u *CollectionUpdate) RemoveTasks(v ...*Task) *CollectionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CollectionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CollectionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CollectionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CollectionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CollectionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := collection.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CollectionUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := collection.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Collection.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := collection.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Collection.platform": %w`, err)}
		}
	}
	return nil
}

func (_u *CollectionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(collection.Table, collection.Columns, sqlgraph.NewFieldSpec(collection.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(collection.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(collection.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(collection.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(collection.FieldPlatform, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RemoteID(); ok {
		_spec.SetField(collection.FieldRemoteID, field.TypeString, value)
	}
	if _u.mutation.RemoteIDCleared() {
		_spec.ClearField(collection.FieldRemoteID, field.TypeString)
	}
	if value, ok := _u.mutation.RemoteData(); ok {
		_spec.SetField(collection.FieldRemoteData, field.TypeJSON, value)
	}
	if _u.mutation.RemoteDataCleared() {
		_spec.ClearField(collection.FieldRemoteData, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(collection.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   collection.TasksTable,
			Columns: []string{collection.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTasksIDs(); len(nodes) > 0 && !_u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   collection.TasksTable,
			Columns: []string{collection.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   collection.TasksTable,
			Columns: []string{collection.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{collection.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CollectionUpdateOne is the builder for updating a single Collection entity.
type CollectionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CollectionMutation
}

// SetName sets the "name" field.
func (_u *CollectionUpdateOne) SetName(v string) *CollectionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CollectionUpdateOne) SetNillableName(v *string) *CollectionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CollectionUpdateOne) SetDescription(v string) *CollectionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CollectionUpdateOne) SetNillableDescription(v *string) *CollectionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *CollectionUpdateOne) ClearDescription() *CollectionUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *CollectionUpdateOne) SetPlatform(v collection.Platform) *CollectionUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *CollectionUpdateOne) SetNillablePlatform(v *collection.Platform) *CollectionUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetRemoteID sets the "remote_id" field.
func (_u *CollectionUpdateOne) SetRemoteID(v string) *CollectionUpdateOne {
	_u.mutation.SetRemoteID(v)
	return _u
}

// SetNillableRemoteID sets the "remote_id" field if the given value is not nil.
func (_u *CollectionUpdateOne) SetNillableRemoteID(v *string) *CollectionUpdateOne {
	if v != nil {
		_u.SetRemoteID(*v)
	}
	return _u
}

// ClearRemoteID clears the value of the "remote_id" field.
func (_u *CollectionUpdateOne) ClearRemoteID() *CollectionUpdateOne {
	_u.mutation.ClearRemoteID()
	return _u
}

// SetRemoteData sets the "remote_data" field.
func (_u *CollectionUpdateOne) SetRemoteData(v map[string]interface{}) *CollectionUpdateOne {
	_u.mutation.SetRemoteData(v)
	return _u
}

// ClearRemoteData clears the value of the "remote_data" field.
func (_u *CollectionUpdateOne) ClearRemoteData() *CollectionUpdateOne {
	_u.mutation.ClearRemoteData()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CollectionUpdateOne) SetUpdatedAt(v time.Time) *CollectionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (_u *CollectionUpdateOne) AddTaskIDs(ids ...uuid.UUID) *CollectionUpdateOne {
	_u.mutation.AddTaskIDs(ids...)
	return _u
}

// AddTasks adds the "tasks" edges to the Task entity.
func (_u *CollectionUpdateOne) AddTasks(v ...*Task) *CollectionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskIDs(ids...)
}

// Mutation returns the CollectionMutation object of the builder.
func (_u *CollectionUpdateOne) Mutation() *CollectionMutation {
	return _u.mutation
}

// ClearTasks clears all "tasks" edges to the Task entity.
func (_u *CollectionUpdateOne) ClearTasks() *CollectionUpdateOne {
	_u.mutation.ClearTasks()
	return _u
}

// RemoveTaskIDs removes the "tasks" edge to Task entities by IDs.
func (_u *CollectionUpdateOne) RemoveTaskIDs(ids ...uuid.UUID) *CollectionUpdateOne {
	_u.mutation.RemoveTaskIDs(ids...)
	return _u
}

// RemoveTasks removes "tasks" edges to Task entities.
func (_u *CollectionUpdateOne) RemoveTasks(v ...*Task) *CollectionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskIDs(ids...)
}

// Where appends a list predicates to the CollectionUpdate builder.
func (_u *CollectionUpdateOne) Where(ps ...predicate.Collection) *CollectionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CollectionUpdateOne) Select(field string, fields ...string) *CollectionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Collection entity.
func (_u *CollectionUpdateOne) Save(ctx context.Context) (*Collection, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CollectionUpdateOne) SaveX(ctx context.Context) *Collection {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CollectionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CollectionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CollectionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := collection.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CollectionUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := collection.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Collection.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := collection.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Collection.platform": %w`, err)}
		}
	}
	return nil
}

func (_u *CollectionUpdateOne) sqlSave(ctx context.Context) (_node *Collection, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(collection.Table, collection.Columns, sqlgraph.NewFieldSpec(collection.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Collection.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, collection.FieldID)
		for _, f := range fields {
			if !collection.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != collection.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(collection.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(collection.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(collection.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(collection.FieldPlatform, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RemoteID(); ok {
		_spec.SetField(collection.FieldRemoteID, field.TypeString, value)
	}
	if _u.mutation.RemoteIDCleared() {
		_spec.ClearField(collection.FieldRemoteID, field.TypeString)
	}
	if value, ok := _u.mutation.RemoteData(); ok {
		_spec.SetField(collection.FieldRemoteData, field.TypeJSON, value)
	}
	if _u.mutation.RemoteDataCleared() {
		_spec.ClearField(collection.FieldRemoteData, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(collection.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   collection.TasksTable,
			Columns: []string{collection.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTasksIDs(); len(nodes) > 0 && !_u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   collection.TasksTable,
			Columns: []string{collection.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   collection.TasksTable,
			Columns: []string{collection.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Collection{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{collection.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
