// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/farmtable-io/farmtable/internal/store/ent/collection"
	"github.com/farmtable-io/farmtable/internal/store/ent/linkedaccount"
	"github.com/google/uuid"
)

// LinkedAccount is the model entity for the LinkedAccount schema.
type LinkedAccount struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CollectionID holds the value of the "collection_id" field.
	CollectionID uuid.UUID `json:"collection_id,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform linkedaccount.Platform `json:"platform,omitempty"`
	// AuthToken holds the value of the "auth_token" field.
	AuthToken string `json:"-"`
	// AuthMethod holds the value of the "auth_method" field.
	AuthMethod linkedaccount.AuthMethod `json:"auth_method,omitempty"`
	// Scopes holds the value of the "scopes" field.
	Scopes []string `json:"scopes,omitempty"`
	// RemoteUserID holds the value of the "remote_user_id" field.
	RemoteUserID string `json:"remote_user_id,omitempty"`
	// Status holds the value of the "status" field.
	Status linkedaccount.Status `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LinkedAccountQuery when eager-loading is set.
	Edges        LinkedAccountEdges `json:"edges"`
	selectValues sql.SelectValues
}

// LinkedAccountEdges holds the relations/edges for other nodes in the graph.
type LinkedAccountEdges struct {
	// Collection holds the value of the collection edge.
	Collection *Collection `json:"collection,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CollectionOrErr returns the Collection value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LinkedAccountEdges) CollectionOrErr() (*Collection, error) {
	if e.Collection != nil {
		return e.Collection, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: collection.Label}
	}
	return nil, &NotLoadedError{edge: "collection"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LinkedAccount) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case linkedaccount.FieldScopes:
			values[i] = new([]byte)
		case linkedaccount.FieldPlatform, linkedaccount.FieldAuthToken, linkedaccount.FieldAuthMethod, linkedaccount.FieldRemoteUserID, linkedaccount.FieldStatus:
			values[i] = new(sql.NullString)
		case linkedaccount.FieldCreatedAt, linkedaccount.FieldUpdatedAt, linkedaccount.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		case linkedaccount.FieldID, linkedaccount.FieldCollectionID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LinkedAccount fields.
func (_m *LinkedAccount) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case linkedaccount.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case linkedaccount.FieldCollectionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field collection_id", values[i])
			} else if value != nil {
				_m.CollectionID = *value
			}
		case linkedaccount.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = linkedaccount.Platform(value.String)
			}
		case linkedaccount.FieldAuthToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_token", values[i])
			} else if value.Valid {
				_m.AuthToken = value.String
			}
		case linkedaccount.FieldAuthMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_method", values[i])
			} else if value.Valid {
				_m.AuthMethod = linkedaccount.AuthMethod(value.String)
			}
		case linkedaccount.FieldScopes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field scopes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Scopes); err != nil {
					return fmt.Errorf("unmarshal field scopes: %w", err)
				}
			}
		case linkedaccount.FieldRemoteUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remote_user_id", values[i])
			} else if value.Valid {
				_m.RemoteUserID = value.String
			}
		case linkedaccount.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = linkedaccount.Status(value.String)
			}
		case linkedaccount.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case linkedaccount.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case linkedaccount.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LinkedAccount.
// This includes values selected through modifiers, order, etc.
func (_m *LinkedAccount) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCollection queries the "collection" edge of the LinkedAccount entity.
func (_m *LinkedAccount) QueryCollection() *CollectionQuery {
	return NewLinkedAccountClient(_m.config).QueryCollection(_m)
}

// Update returns a builder for updating this LinkedAccount.
// Note that you need to call LinkedAccount.Unwrap() before calling this method if this LinkedAccount
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LinkedAccount) Update() *LinkedAccountUpdateOne {
	return NewLinkedAccountClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LinkedAccount entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LinkedAccount) Unwrap() *LinkedAccount {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LinkedAccount is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LinkedAccount) String() string {
	var builder strings.Builder
	builder.WriteString("LinkedAccount(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("collection_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CollectionID))
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(fmt.Sprintf("%v", _m.Platform))
	builder.WriteString(", ")
	builder.WriteString("auth_token=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("auth_method=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuthMethod))
	builder.WriteString(", ")
	builder.WriteString("scopes=")
	builder.WriteString(fmt.Sprintf("%v", _m.Scopes))
	builder.WriteString(", ")
	builder.WriteString("remote_user_id=")
	builder.WriteString(_m.RemoteUserID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// LinkedAccounts is a parsable slice of LinkedAccount.
type LinkedAccounts []*LinkedAccount
