// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/farmtable-io/farmtable/internal/store/ent/collection"
	"github.com/farmtable-io/farmtable/internal/store/ent/linkedaccount"
	"github.com/farmtable-io/farmtable/internal/store/ent/predicate"
	"github.com/google/uuid"
)

// LinkedAccountUpdate is the builder for updating LinkedAccount entities.
type LinkedAccountUpdate struct {
	config
	hooks    []Hook
	mutation *LinkedAccountMutation
}

// Where appends a list predicates to the LinkedAccountUpdate builder.
func (_u *LinkedAccountUpdate) Where(ps ...predicate.LinkedAccount) *LinkedAccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCollectionID sets the "collection_id" field.
func (_u *LinkedAccountUpdate) SetCollectionID(v uuid.UUID) *LinkedAccountUpdate {
	_u.mutation.SetCollectionID(v)
	return _u
}

// SetNillableCollectionID sets the "collection_id" field if the given value is not nil.
func (_u *LinkedAccountUpdate) SetNillableCollectionID(v *uuid.UUID) *LinkedAccountUpdate {
	if v != nil {
		_u.SetCollectionID(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *LinkedAccountUpdate) SetPlatform(v linkedaccount.Platform) *LinkedAccountUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *LinkedAccountUpdate) SetNillablePlatform(v *linkedaccount.Platform) *LinkedAccountUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetAuthToken sets the "auth_token" field.
func (_u *LinkedAccountUpdate) SetAuthToken(v string) *LinkedAccountUpdate {
	_u.mutation.SetAuthToken(v)
	return _u
}

// SetNillableAuthToken sets the "auth_token" field if the given value is not nil.
func (_u *LinkedAccountUpdate) SetNillableAuthToken(v *string) *LinkedAccountUpdate {
	if v != nil {
		_u.SetAuthToken(*v)
	}
	return _u
}

// SetAuthMethod sets the "auth_method" field.
func (_u *LinkedAccountUpdate) SetAuthMethod(v linkedaccount.AuthMethod) *LinkedAccountUpdate {
	_u.mutation.SetAuthMethod(v)
	return _u
}

// SetNillableAuthMethod sets the "auth_method" field if the given value is not nil.
func (_u *LinkedAccountUpdate) SetNillableAuthMethod(v *linkedaccount.AuthMethod) *LinkedAccountUpdate {
	if v != nil {
		_u.SetAuthMethod(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *LinkedAccountUpdate) SetScopes(v []string) *LinkedAccountUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *LinkedAccountUpdate) AppendScopes(v []string) *LinkedAccountUpdate {
	_u.mutation.AppendScopes(v)
	return _u
}

// ClearScopes clears the value of the "scopes" field.
func (_u *LinkedAccountUpdate) ClearScopes() *LinkedAccountUpdate {
	_u.mutation.ClearScopes()
	return _u
}

// SetRemoteUserID sets the "remote_user_id" field.
func (_u *LinkedAccountUpdate) SetRemoteUserID(v string) *LinkedAccountUpdate {
	_u.mutation.SetRemoteUserID(v)
	return _u
}

// SetNillableRemoteUserID sets the "remote_user_id" field if the given value is not nil.
func (_u *LinkedAccountUpdate) SetNillableRemoteUserID(v *string) *LinkedAccountUpdate {
	if v != nil {
		_u.SetRemoteUserID(*v)
	}
	return _u
}

// ClearRemoteUserID clears the value of the "remote_user_id" field.
func (_u *LinkedAccountUpdate) ClearRemoteUserID() *LinkedAccountUpdate {
	_u.mutation.ClearRemoteUserID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *LinkedAccountUpdate) SetStatus(v linkedaccount.Status) *LinkedAccountUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *LinkedAccountUpdate) SetNillableStatus(v *linkedaccount.Status) *LinkedAccountUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LinkedAccountUpdate) SetUpdatedAt(v time.Time) *LinkedAccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *LinkedAccountUpdate) SetExpiresAt(v time.Time) *LinkedAccountUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *LinkedAccountUpdate) SetNillableExpiresAt(v *time.Time) *LinkedAccountUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *LinkedAccountUpdate) ClearExpiresAt() *LinkedAccountUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *LinkedAccountUpdate) SetRefreshToken(v string) *LinkedAccountUpdate {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *LinkedAccountUpdate) SetNillableRefreshToken(v *string) *LinkedAccountUpdate {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (_u *LinkedAccountUpdate) ClearRefreshToken() *LinkedAccountUpdate {
	_u.mutation.ClearRefreshToken()
	return _u
}

// SetTokenExpiry sets the "token_expiry" field.
func (_u *LinkedAccountUpdate) SetTokenExpiry(v time.Time) *LinkedAccountUpdate {
	_u.mutation.SetTokenExpiry(v)
	return _u
}

// SetNillableTokenExpiry sets the "token_expiry" field if the given value is not nil.
func (_u *LinkedAccountUpdate) SetNillableTokenExpiry(v *time.Time) *LinkedAccountUpdate {
	if v != nil {
		_u.SetTokenExpiry(*v)
	}
	return _u
}

// ClearTokenExpiry clears the value of the "token_expiry" field.
func (_u *LinkedAccountUpdate) ClearTokenExpiry() *LinkedAccountUpdate {
	_u.mutation.ClearTokenExpiry()
	return _u
}

// SetScopesGranted sets the "scopes_granted" field.
func (_u *LinkedAccountUpdate) SetScopesGranted(v []string) *LinkedAccountUpdate {
	_u.mutation.SetScopesGranted(v)
	return _u
}

// AppendScopesGranted appends value to the "scopes_granted" field.
func (_u *LinkedAccountUpdate) AppendScopesGranted(v []string) *LinkedAccountUpdate {
	_u.mutation.AppendScopesGranted(v)
	return _u
}

// ClearScopesGranted clears the value of the "scopes_granted" field.
func (_u *LinkedAccountUpdate) ClearScopesGranted() *LinkedAccountUpdate {
	_u.mutation.ClearScopesGranted()
	return _u
}

// SetLastValidatedAt sets the "last_validated_at" field.
func (_u *LinkedAccountUpdate) SetLastValidatedAt(v time.Time) *LinkedAccountUpdate {
	_u.mutation.SetLastValidatedAt(v)
	return _u
}

// SetNillableLastValidatedAt sets the "last_validated_at" field if the given value is not nil.
func (_u *LinkedAccountUpdate) SetNillableLastValidatedAt(v *time.Time) *LinkedAccountUpdate {
	if v != nil {
		_u.SetLastValidatedAt(*v)
	}
	return _u
}

// ClearLastValidatedAt clears the value of the "last_validated_at" field.
func (_u *LinkedAccountUpdate) ClearLastValidatedAt() *LinkedAccountUpdate {
	_u.mutation.ClearLastValidatedAt()
	return _u
}

// SetCollection sets the "collection" edge to the Collection entity.
func (_u *LinkedAccountUpdate) SetCollection(v *Collection) *LinkedAccountUpdate {
	return _u.SetCollectionID(v.ID)
}

// Mutation returns the LinkedAccountMutation object of the builder.
func (_u *LinkedAccountUpdate) Mutation() *LinkedAccountMutation {
	return _u.mutation
}

// ClearCollection clears the "collection" edge to the Collection entity.
func (_u *LinkedAccountUpdate) ClearCollection() *LinkedAccountUpdate {
	_u.mutation.ClearCollection()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LinkedAccountUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LinkedAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LinkedAccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LinkedAccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LinkedAccountUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := linkedaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LinkedAccountUpdate) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := linkedaccount.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "LinkedAccount.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthMethod(); ok {
		if err := linkedaccount.AuthMethodValidator(v); err != nil {
			return &ValidationError{Name: "auth_method", err: fmt.Errorf(`ent: validator failed for field "LinkedAccount.auth_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := linkedaccount.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LinkedAccount.status": %w`, err)}
		}
	}
	if _u.mutation.CollectionCleared() && len(_u.mutation.CollectionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LinkedAccount.collection"`)
	}
	return nil
}

func (_u *LinkedAccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(linkedaccount.Table, linkedaccount.Columns, sqlgraph.NewFieldSpec(linkedaccount.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(linkedaccount.FieldPlatform, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AuthToken(); ok {
		_spec.SetField(linkedaccount.FieldAuthToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthMethod(); ok {
		_spec.SetField(linkedaccount.FieldAuthMethod, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(linkedaccount.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, linkedaccount.FieldScopes, value)
		})
	}
	if _u.mutation.ScopesCleared() {
		_spec.ClearField(linkedaccount.FieldScopes, field.TypeJSON)
	}
	if value, ok := _u.mutation.RemoteUserID(); ok {
		_spec.SetField(linkedaccount.FieldRemoteUserID, field.TypeString, value)
	}
	if _u.mutation.RemoteUserIDCleared() {
		_spec.ClearField(linkedaccount.FieldRemoteUserID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(linkedaccount.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(linkedaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(linkedaccount.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(linkedaccount.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(linkedaccount.FieldRefreshToken, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenCleared() {
		_spec.ClearField(linkedaccount.FieldRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.TokenExpiry(); ok {
		_spec.SetField(linkedaccount.FieldTokenExpiry, field.TypeTime, value)
	}
	if _u.mutation.TokenExpiryCleared() {
		_spec.ClearField(linkedaccount.FieldTokenExpiry, field.TypeTime)
	}
	if value, ok := _u.mutation.ScopesGranted(); ok {
		_spec.SetField(linkedaccount.FieldScopesGranted, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopesGranted(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, linkedaccount.FieldScopesGranted, value)
		})
	}
	if _u.mutation.ScopesGrantedCleared() {
		_spec.ClearField(linkedaccount.FieldScopesGranted, field.TypeJSON)
	}
	if value, ok := _u.mutation.LastValidatedAt(); ok {
		_spec.SetField(linkedaccount.FieldLastValidatedAt, field.TypeTime, value)
	}
	if _u.mutation.LastValidatedAtCleared() {
		_spec.ClearField(linkedaccount.FieldLastValidatedAt, field.TypeTime)
	}
	if _u.mutation.CollectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   linkedaccount.CollectionTable,
			Columns: []string{linkedaccount.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CollectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   linkedaccount.CollectionTable,
			Columns: []string{linkedaccount.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{linkedaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LinkedAccountUpdateOne is the builder for updating a single LinkedAccount entity.
type LinkedAccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LinkedAccountMutation
}

// SetCollectionID sets the "collection_id" field.
func (_u *LinkedAccountUpdateOne) SetCollectionID(v uuid.UUID) *LinkedAccountUpdateOne {
	_u.mutation.SetCollectionID(v)
	return _u
}

// SetNillableCollectionID sets the "collection_id" field if the given value is not nil.
func (_u *LinkedAccountUpdateOne) SetNillableCollectionID(v *uuid.UUID) *LinkedAccountUpdateOne {
	if v != nil {
		_u.SetCollectionID(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *LinkedAccountUpdateOne) SetPlatform(v linkedaccount.Platform) *LinkedAccountUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *LinkedAccountUpdateOne) SetNillablePlatform(v *linkedaccount.Platform) *LinkedAccountUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetAuthToken sets the "auth_token" field.
func (_u *LinkedAccountUpdateOne) SetAuthToken(v string) *LinkedAccountUpdateOne {
	_u.mutation.SetAuthToken(v)
	return _u
}

// SetNillableAuthToken sets the "auth_token" field if the given value is not nil.
func (_u *LinkedAccountUpdateOne) SetNillableAuthToken(v *string) *LinkedAccountUpdateOne {
	if v != nil {
		_u.SetAuthToken(*v)
	}
	return _u
}

// SetAuthMethod sets the "auth_method" field.
func (_u *LinkedAccountUpdateOne) SetAuthMethod(v linkedaccount.AuthMethod) *LinkedAccountUpdateOne {
	_u.mutation.SetAuthMethod(v)
	return _u
}

// SetNillableAuthMethod sets the "auth_method" field if the given value is not nil.
func (_u *LinkedAccountUpdateOne) SetNillableAuthMethod(v *linkedaccount.AuthMethod) *LinkedAccountUpdateOne {
	if v != nil {
		_u.SetAuthMethod(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *LinkedAccountUpdateOne) SetScopes(v []string) *LinkedAccountUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *LinkedAccountUpdateOne) AppendScopes(v []string) *LinkedAccountUpdateOne {
	_u.mutation.AppendScopes(v)
	return _u
}

// ClearScopes clears the value of the "scopes" field.
func (_u *LinkedAccountUpdateOne) ClearScopes() *LinkedAccountUpdateOne {
	_u.mutation.ClearScopes()
	return _u
}

// SetRemoteUserID sets the "remote_user_id" field.
func (_u *LinkedAccountUpdateOne) SetRemoteUserID(v string) *LinkedAccountUpdateOne {
	_u.mutation.SetRemoteUserID(v)
	return _u
}

// SetNillableRemoteUserID sets the "remote_user_id" field if the given value is not nil.
func (_u *LinkedAccountUpdateOne) SetNillableRemoteUserID(v *string) *LinkedAccountUpdateOne {
	if v != nil {
		_u.SetRemoteUserID(*v)
	}
	return _u
}

// ClearRemoteUserID clears the value of the "remote_user_id" field.
func (_u *LinkedAccountUpdateOne) ClearRemoteUserID() *LinkedAccountUpdateOne {
	_u.mutation.ClearRemoteUserID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *LinkedAccountUpdateOne) SetStatus(v linkedaccount.Status) *LinkedAccountUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *LinkedAccountUpdateOne) SetNillableStatus(v *linkedaccount.Status) *LinkedAccountUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LinkedAccountUpdateOne) SetUpdatedAt(v time.Time) *LinkedAccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *LinkedAccountUpdateOne) SetExpiresAt(v time.Time) *LinkedAccountUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *LinkedAccountUpdateOne) SetNillableExpiresAt(v *time.Time) *LinkedAccountUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *LinkedAccountUpdateOne) ClearExpiresAt() *LinkedAccountUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *LinkedAccountUpdateOne) SetRefreshToken(v string) *LinkedAccountUpdateOne {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *LinkedAccountUpdateOne) SetNillableRefreshToken(v *string) *LinkedAccountUpdateOne {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (_u *LinkedAccountUpdateOne) ClearRefreshToken() *LinkedAccountUpdateOne {
	_u.mutation.ClearRefreshToken()
	return _u
}

// SetTokenExpiry sets the "token_expiry" field.
func (_u *LinkedAccountUpdateOne) SetTokenExpiry(v time.Time) *LinkedAccountUpdateOne {
	_u.mutation.SetTokenExpiry(v)
	return _u
}

// SetNillableTokenExpiry sets the "token_expiry" field if the given value is not nil.
func (_u *LinkedAccountUpdateOne) SetNillableTokenExpiry(v *time.Time) *LinkedAccountUpdateOne {
	if v != nil {
		_u.SetTokenExpiry(*v)
	}
	return _u
}

// ClearTokenExpiry clears the value of the "token_expiry" field.
func (_u *LinkedAccountUpdateOne) ClearTokenExpiry() *LinkedAccountUpdateOne {
	_u.mutation.ClearTokenExpiry()
	return _u
}

// SetScopesGranted sets the "scopes_granted" field.
func (_u *LinkedAccountUpdateOne) SetScopesGranted(v []string) *LinkedAccountUpdateOne {
	_u.mutation.SetScopesGranted(v)
	return _u
}

// AppendScopesGranted appends value to the "scopes_granted" field.
func (_u *LinkedAccountUpdateOne) AppendScopesGranted(v []string) *LinkedAccountUpdateOne {
	_u.mutation.AppendScopesGranted(v)
	return _u
}

// ClearScopesGranted clears the value of the "scopes_granted" field.
func (_u *LinkedAccountUpdateOne) ClearScopesGranted() *LinkedAccountUpdateOne {
	_u.mutation.ClearScopesGranted()
	return _u
}

// SetLastValidatedAt sets the "last_validated_at" field.
func (_u *LinkedAccountUpdateOne) SetLastValidatedAt(v time.Time) *LinkedAccountUpdateOne {
	_u.mutation.SetLastValidatedAt(v)
	return _u
}

// SetNillableLastValidatedAt sets the "last_validated_at" field if the given value is not nil.
func (_u *LinkedAccountUpdateOne) SetNillableLastValidatedAt(v *time.Time) *LinkedAccountUpdateOne {
	if v != nil {
		_u.SetLastValidatedAt(*v)
	}
	return _u
}

// ClearLastValidatedAt clears the value of the "last_validated_at" field.
func (_u *LinkedAccountUpdateOne) ClearLastValidatedAt() *LinkedAccountUpdateOne {
	_u.mutation.ClearLastValidatedAt()
	return _u
}

// SetCollection sets the "collection" edge to the Collection entity.
func (_u *LinkedAccountUpdateOne) SetCollection(v *Collection) *LinkedAccountUpdateOne {
	return _u.SetCollectionID(v.ID)
}

// Mutation returns the LinkedAccountMutation object of the builder.
func (_u *LinkedAccountUpdateOne) Mutation() *LinkedAccountMutation {
	return _u.mutation
}

// ClearCollection clears the "collection" edge to the Collection entity.
func (_u *LinkedAccountUpdateOne) ClearCollection() *LinkedAccountUpdateOne {
	_u.mutation.ClearCollection()
	return _u
}

// Where appends a list predicates to the LinkedAccountUpdate builder.
func (_u *LinkedAccountUpdateOne) Where(ps ...predicate.LinkedAccount) *LinkedAccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LinkedAccountUpdateOne) Select(field string, fields ...string) *LinkedAccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LinkedAccount entity.
func (_u *LinkedAccountUpdateOne) Save(ctx context.Context) (*LinkedAccount, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LinkedAccountUpdateOne) SaveX(ctx context.Context) *LinkedAccount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LinkedAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LinkedAccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LinkedAccountUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := linkedaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LinkedAccountUpdateOne) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := linkedaccount.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "LinkedAccount.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthMethod(); ok {
		if err := linkedaccount.AuthMethodValidator(v); err != nil {
			return &ValidationError{Name: "auth_method", err: fmt.Errorf(`ent: validator failed for field "LinkedAccount.auth_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := linkedaccount.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LinkedAccount.status": %w`, err)}
		}
	}
	if _u.mutation.CollectionCleared() && len(_u.mutation.CollectionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LinkedAccount.collection"`)
	}
	return nil
}

func (_u *LinkedAccountUpdateOne) sqlSave(ctx context.Context) (_node *LinkedAccount, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(linkedaccount.Table, linkedaccount.Columns, sqlgraph.NewFieldSpec(linkedaccount.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LinkedAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, linkedaccount.FieldID)
		for _, f := range fields {
			if !linkedaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != linkedaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(linkedaccount.FieldPlatform, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AuthToken(); ok {
		_spec.SetField(linkedaccount.FieldAuthToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthMethod(); ok {
		_spec.SetField(linkedaccount.FieldAuthMethod, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(linkedaccount.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, linkedaccount.FieldScopes, value)
		})
	}
	if _u.mutation.ScopesCleared() {
		_spec.ClearField(linkedaccount.FieldScopes, field.TypeJSON)
	}
	if value, ok := _u.mutation.RemoteUserID(); ok {
		_spec.SetField(linkedaccount.FieldRemoteUserID, field.TypeString, value)
	}
	if _u.mutation.RemoteUserIDCleared() {
		_spec.ClearField(linkedaccount.FieldRemoteUserID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(linkedaccount.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(linkedaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(linkedaccount.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(linkedaccount.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(linkedaccount.FieldRefreshToken, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenCleared() {
		_spec.ClearField(linkedaccount.FieldRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.TokenExpiry(); ok {
		_spec.SetField(linkedaccount.FieldTokenExpiry, field.TypeTime, value)
	}
	if _u.mutation.TokenExpiryCleared() {
		_spec.ClearField(linkedaccount.FieldTokenExpiry, field.TypeTime)
	}
	if value, ok := _u.mutation.ScopesGranted(); ok {
		_spec.SetField(linkedaccount.FieldScopesGranted, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopesGranted(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, linkedaccount.FieldScopesGranted, value)
		})
	}
	if _u.mutation.ScopesGrantedCleared() {
		_spec.ClearField(linkedaccount.FieldScopesGranted, field.TypeJSON)
	}
	if value, ok := _u.mutation.LastValidatedAt(); ok {
		_spec.SetField(linkedaccount.FieldLastValidatedAt, field.TypeTime, value)
	}
	if _u.mutation.LastValidatedAtCleared() {
		_spec.ClearField(linkedaccount.FieldLastValidatedAt, field.TypeTime)
	}
	if _u.mutation.CollectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   linkedaccount.CollectionTable,
			Columns: []string{linkedaccount.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CollectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   linkedaccount.CollectionTable,
			Columns: []string{linkedaccount.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LinkedAccount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{linkedaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
