// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/farmtable-io/farmtable/internal/store/ent/relationship"
	"github.com/farmtable-io/farmtable/internal/store/ent/task"
	"github.com/google/uuid"
)

// Relationship is the model entity for the Relationship schema.
type Relationship struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// SourceTaskID holds the value of the "source_task_id" field.
	SourceTaskID uuid.UUID `json:"source_task_id,omitempty"`
	// TargetTaskID holds the value of the "target_task_id" field.
	TargetTaskID uuid.UUID `json:"target_task_id,omitempty"`
	// Type holds the value of the "type" field.
	Type relationship.Type `json:"type,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RelationshipQuery when eager-loading is set.
	Edges        RelationshipEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RelationshipEdges holds the relations/edges for other nodes in the graph.
type RelationshipEdges struct {
	// SourceTask holds the value of the source_task edge.
	SourceTask *Task `json:"source_task,omitempty"`
	// TargetTask holds the value of the target_task edge.
	TargetTask *Task `json:"target_task,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SourceTaskOrErr returns the SourceTask value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RelationshipEdges) SourceTaskOrErr() (*Task, error) {
	if e.SourceTask != nil {
		return e.SourceTask, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "source_task"}
}

// TargetTaskOrErr returns the TargetTask value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RelationshipEdges) TargetTaskOrErr() (*Task, error) {
	if e.TargetTask != nil {
		return e.TargetTask, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "target_task"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Relationship) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case relationship.FieldType:
			values[i] = new(sql.NullString)
		case relationship.FieldID, relationship.FieldSourceTaskID, relationship.FieldTargetTaskID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Relationship fields.
func (_m *Relationship) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case relationship.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case relationship.FieldSourceTaskID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field source_task_id", values[i])
			} else if value != nil {
				_m.SourceTaskID = *value
			}
		case relationship.FieldTargetTaskID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field target_task_id", values[i])
			} else if value != nil {
				_m.TargetTaskID = *value
			}
		case relationship.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = relationship.Type(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Relationship.
// This includes values selected through modifiers, order, etc.
func (_m *Relationship) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySourceTask queries the "source_task" edge of the Relationship entity.
func (_m *Relationship) QuerySourceTask() *TaskQuery {
	return NewRelationshipClient(_m.config).QuerySourceTask(_m)
}

// QueryTargetTask queries the "target_task" edge of the Relationship entity.
func (_m *Relationship) QueryTargetTask() *TaskQuery {
	return NewRelationshipClient(_m.config).QueryTargetTask(_m)
}

// Update returns a builder for updating this Relationship.
// Note that you need to call Relationship.Unwrap() before calling this method if this Relationship
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Relationship) Update() *RelationshipUpdateOne {
	return NewRelationshipClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Relationship entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Relationship) Unwrap() *Relationship {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Relationship is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Relationship) String() string {
	var builder strings.Builder
	builder.WriteString("Relationship(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("source_task_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceTaskID))
	builder.WriteString(", ")
	builder.WriteString("target_task_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetTaskID))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteByte(')')
	return builder.String()
}

// Relationships is a parsable slice of Relationship.
type Relationships []*Relationship
