// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/farmtable-io/farmtable/internal/store/ent/collection"
	"github.com/farmtable-io/farmtable/internal/store/ent/task"
	"github.com/google/uuid"
)

// Task is the model entity for the Task schema.
type Task struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Phase holds the value of the "phase" field.
	Phase task.Phase `json:"phase,omitempty"`
	// Stage holds the value of the "stage" field.
	Stage task.Stage `json:"stage,omitempty"`
	// NativeLabel holds the value of the "native_label" field.
	NativeLabel string `json:"native_label,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority *task.Priority `json:"priority,omitempty"`
	// AssigneeID holds the value of the "assignee_id" field.
	AssigneeID *uuid.UUID `json:"assignee_id,omitempty"`
	// CollectionID holds the value of the "collection_id" field.
	CollectionID uuid.UUID `json:"collection_id,omitempty"`
	// ParentTaskID holds the value of the "parent_task_id" field.
	ParentTaskID *uuid.UUID `json:"parent_task_id,omitempty"`
	// StartDate holds the value of the "start_date" field.
	StartDate *time.Time `json:"start_date,omitempty"`
	// DueDate holds the value of the "due_date" field.
	DueDate *time.Time `json:"due_date,omitempty"`
	// ClosedAt holds the value of the "closed_at" field.
	ClosedAt *time.Time `json:"closed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AcceptanceCriteria holds the value of the "acceptance_criteria" field.
	AcceptanceCriteria *string `json:"acceptance_criteria,omitempty"`
	// RemoteData holds the value of the "remote_data" field.
	RemoteData map[string]interface{} `json:"remote_data,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TaskQuery when eager-loading is set.
	Edges        TaskEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TaskEdges holds the relations/edges for other nodes in the graph.
type TaskEdges struct {
	// Collection holds the value of the collection edge.
	Collection *Collection `json:"collection,omitempty"`
	// Parent holds the value of the parent edge.
	Parent *Task `json:"parent,omitempty"`
	// Children holds the value of the children edge.
	Children []*Task `json:"children,omitempty"`
	// Comments holds the value of the comments edge.
	Comments []*Comment `json:"comments,omitempty"`
	// Changes holds the value of the changes edge.
	Changes []*Change `json:"changes,omitempty"`
	// SourceRelationships holds the value of the source_relationships edge.
	SourceRelationships []*Relationship `json:"source_relationships,omitempty"`
	// TargetRelationships holds the value of the target_relationships edge.
	TargetRelationships []*Relationship `json:"target_relationships,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [7]bool
}

// CollectionOrErr returns the Collection value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) CollectionOrErr() (*Collection, error) {
	if e.Collection != nil {
		return e.Collection, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: collection.Label}
	}
	return nil, &NotLoadedError{edge: "collection"}
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) ParentOrErr() (*Task, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) ChildrenOrErr() ([]*Task, error) {
	if e.loadedTypes[2] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{edge: "children"}
}

// CommentsOrErr returns the Comments value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) CommentsOrErr() ([]*Comment, error) {
	if e.loadedTypes[3] {
		return e.Comments, nil
	}
	return nil, &NotLoadedError{edge: "comments"}
}

// ChangesOrErr returns the Changes value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) ChangesOrErr() ([]*Change, error) {
	if e.loadedTypes[4] {
		return e.Changes, nil
	}
	return nil, &NotLoadedError{edge: "changes"}
}

// SourceRelationshipsOrErr returns the SourceRelationships value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) SourceRelationshipsOrErr() ([]*Relationship, error) {
	if e.loadedTypes[5] {
		return e.SourceRelationships, nil
	}
	return nil, &NotLoadedError{edge: "source_relationships"}
}

// TargetRelationshipsOrErr returns the TargetRelationships value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) TargetRelationshipsOrErr() ([]*Relationship, error) {
	if e.loadedTypes[6] {
		return e.TargetRelationships, nil
	}
	return nil, &NotLoadedError{edge: "target_relationships"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Task) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case task.FieldAssigneeID, task.FieldParentTaskID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case task.FieldRemoteData:
			values[i] = new([]byte)
		case task.FieldTitle, task.FieldDescription, task.FieldPhase, task.FieldStage, task.FieldNativeLabel, task.FieldType, task.FieldPriority, task.FieldAcceptanceCriteria, task.FieldVersion:
			values[i] = new(sql.NullString)
		case task.FieldStartDate, task.FieldDueDate, task.FieldClosedAt, task.FieldCreatedAt, task.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case task.FieldID, task.FieldCollectionID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Task fields.
func (_m *Task) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case task.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case task.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case task.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case task.FieldPhase:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phase", values[i])
			} else if value.Valid {
				_m.Phase = task.Phase(value.String)
			}
		case task.FieldStage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stage", values[i])
			} else if value.Valid {
				_m.Stage = task.Stage(value.String)
			}
		case task.FieldNativeLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field native_label", values[i])
			} else if value.Valid {
				_m.NativeLabel = value.String
			}
		case task.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case task.FieldPriority:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = new(task.Priority)
				*_m.Priority = task.Priority(value.String)
			}
		case task.FieldAssigneeID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field assignee_id", values[i])
			} else if value.Valid {
				_m.AssigneeID = new(uuid.UUID)
				*_m.AssigneeID = *value.S.(*uuid.UUID)
			}
		case task.FieldCollectionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field collection_id", values[i])
			} else if value != nil {
				_m.CollectionID = *value
			}
		case task.FieldParentTaskID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field parent_task_id", values[i])
			} else if value.Valid {
				_m.ParentTaskID = new(uuid.UUID)
				*_m.ParentTaskID = *value.S.(*uuid.UUID)
			}
		case task.FieldStartDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_date", values[i])
			} else if value.Valid {
				_m.StartDate = new(time.Time)
				*_m.StartDate = value.Time
			}
		case task.FieldDueDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field due_date", values[i])
			} else if value.Valid {
				_m.DueDate = new(time.Time)
				*_m.DueDate = value.Time
			}
		case task.FieldClosedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field closed_at", values[i])
			} else if value.Valid {
				_m.ClosedAt = new(time.Time)
				*_m.ClosedAt = value.Time
			}
		case task.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case task.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case task.FieldAcceptanceCriteria:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field acceptance_criteria", values[i])
			} else if value.Valid {
				_m.AcceptanceCriteria = new(string)
				*_m.AcceptanceCriteria = value.String
			}
		case task.FieldRemoteData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field remote_data", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RemoteData); err != nil {
					return fmt.Errorf("unmarshal field remote_data: %w", err)
				}
			}
		case task.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Task.
// This includes values selected through modifiers, order, etc.
func (_m *Task) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCollection queries the "collection" edge of the Task entity.
func (_m *Task) QueryCollection() *CollectionQuery {
	return NewTaskClient(_m.config).QueryCollection(_m)
}

// QueryParent queries the "parent" edge of the Task entity.
func (_m *Task) QueryParent() *TaskQuery {
	return NewTaskClient(_m.config).QueryParent(_m)
}

// QueryChildren queries the "children" edge of the Task entity.
func (_m *Task) QueryChildren() *TaskQuery {
	return NewTaskClient(_m.config).QueryChildren(_m)
}

// QueryComments queries the "comments" edge of the Task entity.
func (_m *Task) QueryComments() *CommentQuery {
	return NewTaskClient(_m.config).QueryComments(_m)
}

// QueryChanges queries the "changes" edge of the Task entity.
func (_m *Task) QueryChanges() *ChangeQuery {
	return NewTaskClient(_m.config).QueryChanges(_m)
}

// QuerySourceRelationships queries the "source_relationships" edge of the Task entity.
func (_m *Task) QuerySourceRelationships() *RelationshipQuery {
	return NewTaskClient(_m.config).QuerySourceRelationships(_m)
}

// QueryTargetRelationships queries the "target_relationships" edge of the Task entity.
func (_m *Task) QueryTargetRelationships() *RelationshipQuery {
	return NewTaskClient(_m.config).QueryTargetRelationships(_m)
}

// Update returns a builder for updating this Task.
// Note that you need to call Task.Unwrap() before calling this method if this Task
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Task) Update() *TaskUpdateOne {
	return NewTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Task entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Task) Unwrap() *Task {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Task is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Task) String() string {
	var builder strings.Builder
	builder.WriteString("Task(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("phase=")
	builder.WriteString(fmt.Sprintf("%v", _m.Phase))
	builder.WriteString(", ")
	builder.WriteString("stage=")
	builder.WriteString(fmt.Sprintf("%v", _m.Stage))
	builder.WriteString(", ")
	builder.WriteString("native_label=")
	builder.WriteString(_m.NativeLabel)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	if v := _m.Priority; v != nil {
		builder.WriteString("priority=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AssigneeID; v != nil {
		builder.WriteString("assignee_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("collection_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CollectionID))
	builder.WriteString(", ")
	if v := _m.ParentTaskID; v != nil {
		builder.WriteString("parent_task_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.StartDate; v != nil {
		builder.WriteString("start_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DueDate; v != nil {
		builder.WriteString("due_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ClosedAt; v != nil {
		builder.WriteString("closed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.AcceptanceCriteria; v != nil {
		builder.WriteString("acceptance_criteria=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("remote_data=")
	builder.WriteString(fmt.Sprintf("%v", _m.RemoteData))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteByte(')')
	return builder.String()
}

// Tasks is a parsable slice of Task.
type Tasks []*Task
