// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/farmtable-io/farmtable/internal/store/ent/change"
	"github.com/farmtable-io/farmtable/internal/store/ent/collection"
	"github.com/farmtable-io/farmtable/internal/store/ent/comment"
	"github.com/farmtable-io/farmtable/internal/store/ent/relationship"
	"github.com/farmtable-io/farmtable/internal/store/ent/task"
	"github.com/google/uuid"
)

// TaskCreate is the builder for creating a Task entity.
type TaskCreate struct {
	config
	mutation *TaskMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *TaskCreate) SetTitle(v string) *TaskCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *TaskCreate) SetDescription(v string) *TaskCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *TaskCreate) SetNillableDescription(v *string) *TaskCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetPhase sets the "phase" field.
func (_c *TaskCreate) SetPhase(v task.Phase) *TaskCreate {
	_c.mutation.SetPhase(v)
	return _c
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (_c *TaskCreate) SetNillablePhase(v *task.Phase) *TaskCreate {
	if v != nil {
		_c.SetPhase(*v)
	}
	return _c
}

// SetStage sets the "stage" field.
func (_c *TaskCreate) SetStage(v task.Stage) *TaskCreate {
	_c.mutation.SetStage(v)
	return _c
}

// SetNillableStage sets the "stage" field if the given value is not nil.
func (_c *TaskCreate) SetNillableStage(v *task.Stage) *TaskCreate {
	if v != nil {
		_c.SetStage(*v)
	}
	return _c
}

// SetNativeLabel sets the "native_label" field.
func (_c *TaskCreate) SetNativeLabel(v string) *TaskCreate {
	_c.mutation.SetNativeLabel(v)
	return _c
}

// SetNillableNativeLabel sets the "native_label" field if the given value is not nil.
func (_c *TaskCreate) SetNillableNativeLabel(v *string) *TaskCreate {
	if v != nil {
		_c.SetNativeLabel(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *TaskCreate) SetType(v string) *TaskCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *TaskCreate) SetNillableType(v *string) *TaskCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *TaskCreate) SetPriority(v task.Priority) *TaskCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *TaskCreate) SetNillablePriority(v *task.Priority) *TaskCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetAssigneeID sets the "assignee_id" field.
func (_c *TaskCreate) SetAssigneeID(v uuid.UUID) *TaskCreate {
	_c.mutation.SetAssigneeID(v)
	return _c
}

// SetNillableAssigneeID sets the "assignee_id" field if the given value is not nil.
func (_c *TaskCreate) SetNillableAssigneeID(v *uuid.UUID) *TaskCreate {
	if v != nil {
		_c.SetAssigneeID(*v)
	}
	return _c
}

// SetCollectionID sets the "collection_id" field.
func (_c *TaskCreate) SetCollectionID(v uuid.UUID) *TaskCreate {
	_c.mutation.SetCollectionID(v)
	return _c
}

// SetParentTaskID sets the "parent_task_id" field.
func (_c *TaskCreate) SetParentTaskID(v uuid.UUID) *TaskCreate {
	_c.mutation.SetParentTaskID(v)
	return _c
}

// SetNillableParentTaskID sets the "parent_task_id" field if the given value is not nil.
func (_c *TaskCreate) SetNillableParentTaskID(v *uuid.UUID) *TaskCreate {
	if v != nil {
		_c.SetParentTaskID(*v)
	}
	return _c
}

// SetStartDate sets the "start_date" field.
func (_c *TaskCreate) SetStartDate(v time.Time) *TaskCreate {
	_c.mutation.SetStartDate(v)
	return _c
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_c *TaskCreate) SetNillableStartDate(v *time.Time) *TaskCreate {
	if v != nil {
		_c.SetStartDate(*v)
	}
	return _c
}

// SetDueDate sets the "due_date" field.
func (_c *TaskCreate) SetDueDate(v time.Time) *TaskCreate {
	_c.mutation.SetDueDate(v)
	return _c
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_c *TaskCreate) SetNillableDueDate(v *time.Time) *TaskCreate {
	if v != nil {
		_c.SetDueDate(*v)
	}
	return _c
}

// SetClosedAt sets the "closed_at" field.
func (_c *TaskCreate) SetClosedAt(v time.Time) *TaskCreate {
	_c.mutation.SetClosedAt(v)
	return _c
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_c *TaskCreate) SetNillableClosedAt(v *time.Time) *TaskCreate {
	if v != nil {
		_c.SetClosedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TaskCreate) SetCreatedAt(v time.Time) *TaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TaskCreate) SetNillableCreatedAt(v *time.Time) *TaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TaskCreate) SetUpdatedAt(v time.Time) *TaskCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TaskCreate) SetNillableUpdatedAt(v *time.Time) *TaskCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAcceptanceCriteria sets the "acceptance_criteria" field.
func (_c *TaskCreate) SetAcceptanceCriteria(v string) *TaskCreate {
	_c.mutation.SetAcceptanceCriteria(v)
	return _c
}

// SetNillableAcceptanceCriteria sets the "acceptance_criteria" field if the given value is not nil.
func (_c *TaskCreate) SetNillableAcceptanceCriteria(v *string) *TaskCreate {
	if v != nil {
		_c.SetAcceptanceCriteria(*v)
	}
	return _c
}

// SetRemoteData sets the "remote_data" field.
func (_c *TaskCreate) SetRemoteData(v map[string]interface{}) *TaskCreate {
	_c.mutation.SetRemoteData(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *TaskCreate) SetVersion(v string) *TaskCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *TaskCreate) SetNillableVersion(v *string) *TaskCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TaskCreate) SetID(v uuid.UUID) *TaskCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TaskCreate) SetNillableID(v *uuid.UUID) *TaskCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetCollection sets the "collection" edge to the Collection entity.
func (_c *TaskCreate) SetCollection(v *Collection) *TaskCreate {
	return _c.SetCollectionID(v.ID)
}

// SetParentID sets the "parent" edge to the Task entity by ID.
func (_c *TaskCreate) SetParentID(id uuid.UUID) *TaskCreate {
	_c.mutation.SetParentID(id)
	return _c
}

// SetNillableParentID sets the "parent" edge to the Task entity by ID if the given value is not nil.
func (_c *TaskCreate) SetNillableParentID(id *uuid.UUID) *TaskCreate {
	if id != nil {
		_c = _c.SetParentID(*id)
	}
	return _c
}

// SetParent sets the "parent" edge to the Task entity.
func (_c *TaskCreate) SetParent(v *Task) *TaskCreate {
	return _c.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Task entity by IDs.
func (_c *TaskCreate) AddChildIDs(ids ...uuid.UUID) *TaskCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the Task entity.
func (_c *TaskCreate) AddChildren(v ...*Task) *TaskCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (_c *TaskCreate) AddCommentIDs(ids ...uuid.UUID) *TaskCreate {
	_c.mutation.AddCommentIDs(ids...)
	return _c
}

// AddComments adds the "comments" edges to the Comment entity.
func (_c *TaskCreate) AddComments(v ...*Comment) *TaskCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCommentIDs(ids...)
}

// AddChangeIDs adds the "changes" edge to the Change entity by IDs.
func (_c *TaskCreate) AddChangeIDs(ids ...uuid.UUID) *TaskCreate {
	_c.mutation.AddChangeIDs(ids...)
	return _c
}

// AddChanges adds the "changes" edges to the Change entity.
func (_c *TaskCreate) AddChanges(v ...*Change) *TaskCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChangeIDs(ids...)
}

// AddSourceRelationshipIDs adds the "source_relationships" edge to the Relationship entity by IDs.
func (_c *TaskCreate) AddSourceRelationshipIDs(ids ...uuid.UUID) *TaskCreate {
	_c.mutation.AddSourceRelationshipIDs(ids...)
	return _c
}

// AddSourceRelationships adds the "source_relationships" edges to the Relationship entity.
func (_c *TaskCreate) AddSourceRelationships(v ...*Relationship) *TaskCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSourceRelationshipIDs(ids...)
}

// AddTargetRelationshipIDs adds the "target_relationships" edge to the Relationship entity by IDs.
func (_c *TaskCreate) AddTargetRelationshipIDs(ids ...uuid.UUID) *TaskCreate {
	_c.mutation.AddTargetRelationshipIDs(ids...)
	return _c
}

// AddTargetRelationships adds the "target_relationships" edges to the Relationship entity.
func (_c *TaskCreate) AddTargetRelationships(v ...*Relationship) *TaskCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTargetRelationshipIDs(ids...)
}

// Mutation returns the TaskMutation object of the builder.
func (_c *TaskCreate) Mutation() *TaskMutation {
	return _c.mutation
}

// Save creates the Task in the database.
func (_c *TaskCreate) Save(ctx context.Context) (*Task, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TaskCreate) SaveX(ctx context.Context) *Task {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TaskCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := task.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Phase(); !ok {
		v := task.DefaultPhase
		_c.mutation.SetPhase(v)
	}
	if _, ok := _c.mutation.Stage(); !ok {
		v := task.DefaultStage
		_c.mutation.SetStage(v)
	}
	if _, ok := _c.mutation.NativeLabel(); !ok {
		v := task.DefaultNativeLabel
		_c.mutation.SetNativeLabel(v)
	}
	if _, ok := _c.mutation.GetType(); !ok {
		v := task.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := task.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := task.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := task.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := task.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TaskCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Task.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := task.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Task.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Phase(); !ok {
		return &ValidationError{Name: "phase", err: errors.New(`ent: missing required field "Task.phase"`)}
	}
	if v, ok := _c.mutation.Phase(); ok {
		if err := task.PhaseValidator(v); err != nil {
			return &ValidationError{Name: "phase", err: fmt.Errorf(`ent: validator failed for field "Task.phase": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Stage(); !ok {
		return &ValidationError{Name: "stage", err: errors.New(`ent: missing required field "Task.stage"`)}
	}
	if v, ok := _c.mutation.Stage(); ok {
		if err := task.StageValidator(v); err != nil {
			return &ValidationError{Name: "stage", err: fmt.Errorf(`ent: validator failed for field "Task.stage": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Priority(); ok {
		if err := task.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Task.priority": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CollectionID(); !ok {
		return &ValidationError{Name: "collection_id", err: errors.New(`ent: missing required field "Task.collection_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Task.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Task.updated_at"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Task.version"`)}
	}
	if len(_c.mutation.CollectionIDs()) == 0 {
		return &ValidationError{Name: "collection", err: errors.New(`ent: missing required edge "Task.collection"`)}
	}
	return nil
}

func (_c *TaskCreate) sqlSave(ctx context.Context) (*Task, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TaskCreate) createSpec() (*Task, *sqlgraph.CreateSpec) {
	var (
		_node = &Task{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(task.Table, sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(task.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(task.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Phase(); ok {
		_spec.SetField(task.FieldPhase, field.TypeEnum, value)
		_node.Phase = value
	}
	if value, ok := _c.mutation.Stage(); ok {
		_spec.SetField(task.FieldStage, field.TypeEnum, value)
		_node.Stage = value
	}
	if value, ok := _c.mutation.NativeLabel(); ok {
		_spec.SetField(task.FieldNativeLabel, field.TypeString, value)
		_node.NativeLabel = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(task.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(task.FieldPriority, field.TypeEnum, value)
		_node.Priority = &value
	}
	if value, ok := _c.mutation.AssigneeID(); ok {
		_spec.SetField(task.FieldAssigneeID, field.TypeUUID, value)
		_node.AssigneeID = &value
	}
	if value, ok := _c.mutation.StartDate(); ok {
		_spec.SetField(task.FieldStartDate, field.TypeTime, value)
		_node.StartDate = &value
	}
	if value, ok := _c.mutation.DueDate(); ok {
		_spec.SetField(task.FieldDueDate, field.TypeTime, value)
		_node.DueDate = &value
	}
	if value, ok := _c.mutation.ClosedAt(); ok {
		_spec.SetField(task.FieldClosedAt, field.TypeTime, value)
		_node.ClosedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(task.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AcceptanceCriteria(); ok {
		_spec.SetField(task.FieldAcceptanceCriteria, field.TypeString, value)
		_node.AcceptanceCriteria = &value
	}
	if value, ok := _c.mutation.RemoteData(); ok {
		_spec.SetField(task.FieldRemoteData, field.TypeJSON, value)
		_node.RemoteData = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(task.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if nodes := _c.mutation.CollectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.CollectionTable,
			Columns: []string{task.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CollectionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ParentTable,
			Columns: []string{task.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ParentTaskID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ChildrenTable,
			Columns: []string{task.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CommentsTable,
			Columns: []string{task.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChangesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ChangesTable,
			Columns: []string{task.ChangesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(change.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SourceRelationshipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.SourceRelationshipsTable,
			Columns: []string{task.SourceRelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TargetRelationshipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.TargetRelationshipsTable,
			Columns: []string{task.TargetRelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TaskCreateBulk is the builder for creating many Task entities in bulk.
type TaskCreateBulk struct {
	config
	err      error
	builders []*TaskCreate
}

// Save creates the Task entities in the database.
func (_c *TaskCreateBulk) Save(ctx context.Context) ([]*Task, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Task, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TaskCreateBulk) SaveX(ctx context.Context) []*Task {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
