// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/farmtable-io/farmtable/internal/store/ent/change"
	"github.com/farmtable-io/farmtable/internal/store/ent/collection"
	"github.com/farmtable-io/farmtable/internal/store/ent/comment"
	"github.com/farmtable-io/farmtable/internal/store/ent/predicate"
	"github.com/farmtable-io/farmtable/internal/store/ent/relationship"
	"github.com/farmtable-io/farmtable/internal/store/ent/task"
	"github.com/google/uuid"
)

// TaskUpdate is the builder for updating Task entities.
type TaskUpdate struct {
	config
	hooks    []Hook
	mutation *TaskMutation
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdate) Where(ps ...predicate.Task) *TaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *TaskUpdate) SetTitle(v string) *TaskUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableTitle(v *string) *TaskUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TaskUpdate) SetDescription(v string) *TaskUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableDescription(v *string) *TaskUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TaskUpdate) ClearDescription() *TaskUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetPhase sets the "phase" field.
func (_u *TaskUpdate) SetPhase(v task.Phase) *TaskUpdate {
	_u.mutation.SetPhase(v)
	return _u
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (_u *TaskUpdate) SetNillablePhase(v *task.Phase) *TaskUpdate {
	if v != nil {
		_u.SetPhase(*v)
	}
	return _u
}

// SetStage sets the "stage" field.
func (_u *TaskUpdate) SetStage(v task.Stage) *TaskUpdate {
	_u.mutation.SetStage(v)
	return _u
}

// SetNillableStage sets the "stage" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableStage(v *task.Stage) *TaskUpdate {
	if v != nil {
		_u.SetStage(*v)
	}
	return _u
}

// SetNativeLabel sets the "native_label" field.
func (_u *TaskUpdate) SetNativeLabel(v string) *TaskUpdate {
	_u.mutation.SetNativeLabel(v)
	return _u
}

// SetNillableNativeLabel sets the "native_label" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableNativeLabel(v *string) *TaskUpdate {
	if v != nil {
		_u.SetNativeLabel(*v)
	}
	return _u
}

// ClearNativeLabel clears the value of the "native_label" field.
func (_u *TaskUpdate) ClearNativeLabel() *TaskUpdate {
	_u.mutation.ClearNativeLabel()
	return _u
}

// SetType sets the "type" field.
func (_u *TaskUpdate) SetType(v string) *TaskUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableType(v *string) *TaskUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// ClearType clears the value of the "type" field.
func (_u *TaskUpdate) ClearType() *TaskUpdate {
	_u.mutation.ClearType()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TaskUpdate) SetPriority(v task.Priority) *TaskUpdate {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TaskUpdate) SetNillablePriority(v *task.Priority) *TaskUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// ClearPriority clears the value of the "priority" field.
func (_u *TaskUpdate) ClearPriority() *TaskUpdate {
	_u.mutation.ClearPriority()
	return _u
}

// SetAssigneeID sets the "assignee_id" field.
func (_u *TaskUpdate) SetAssigneeID(v uuid.UUID) *TaskUpdate {
	_u.mutation.SetAssigneeID(v)
	return _u
}

// SetNillableAssigneeID sets the "assignee_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableAssigneeID(v *uuid.UUID) *TaskUpdate {
	if v != nil {
		_u.SetAssigneeID(*v)
	}
	return _u
}

// ClearAssigneeID clears the value of the "assignee_id" field.
func (_u *TaskUpdate) ClearAssigneeID() *TaskUpdate {
	_u.mutation.ClearAssigneeID()
	return _u
}

// SetCollectionID sets the "collection_id" field.
func (_u *TaskUpdate) SetCollectionID(v uuid.UUID) *TaskUpdate {
	_u.mutation.SetCollectionID(v)
	return _u
}

// SetNillableCollectionID sets the "collection_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableCollectionID(v *uuid.UUID) *TaskUpdate {
	if v != nil {
		_u.SetCollectionID(*v)
	}
	return _u
}

// SetParentTaskID sets the "parent_task_id" field.
func (_u *TaskUpdate) SetParentTaskID(v uuid.UUID) *TaskUpdate {
	_u.mutation.SetParentTaskID(v)
	return _u
}

// SetNillableParentTaskID sets the "parent_task_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableParentTaskID(v *uuid.UUID) *TaskUpdate {
	if v != nil {
		_u.SetParentTaskID(*v)
	}
	return _u
}

// ClearParentTaskID clears the value of the "parent_task_id" field.
func (_u *TaskUpdate) ClearParentTaskID() *TaskUpdate {
	_u.mutation.ClearParentTaskID()
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *TaskUpdate) SetStartDate(v time.Time) *TaskUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableStartDate(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// ClearStartDate clears the value of the "start_date" field.
func (_u *TaskUpdate) ClearStartDate() *TaskUpdate {
	_u.mutation.ClearStartDate()
	return _u
}

// SetDueDate sets the "due_date" field.
func (_u *TaskUpdate) SetDueDate(v time.Time) *TaskUpdate {
	_u.mutation.SetDueDate(v)
	return _u
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableDueDate(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetDueDate(*v)
	}
	return _u
}

// ClearDueDate clears the value of the "due_date" field.
func (_u *TaskUpdate) ClearDueDate() *TaskUpdate {
	_u.mutation.ClearDueDate()
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *TaskUpdate) SetClosedAt(v time.Time) *TaskUpdate {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableClosedAt(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *TaskUpdate) ClearClosedAt() *TaskUpdate {
	_u.mutation.ClearClosedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskUpdate) SetUpdatedAt(v time.Time) *TaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAcceptanceCriteria sets the "acceptance_criteria" field.
func (_u *TaskUpdate) SetAcceptanceCriteria(v string) *TaskUpdate {
	_u.mutation.SetAcceptanceCriteria(v)
	return _u
}

// SetNillableAcceptanceCriteria sets the "acceptance_criteria" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableAcceptanceCriteria(v *string) *TaskUpdate {
	if v != nil {
		_u.SetAcceptanceCriteria(*v)
	}
	return _u
}

// ClearAcceptanceCriteria clears the value of the "acceptance_criteria" field.
func (_u *TaskUpdate) ClearAcceptanceCriteria() *TaskUpdate {
	_u.mutation.ClearAcceptanceCriteria()
	return _u
}

// SetRemoteData sets the "remote_data" field.
func (_u *TaskUpdate) SetRemoteData(v map[string]interface{}) *TaskUpdate {
	_u.mutation.SetRemoteData(v)
	return _u
}

// ClearRemoteData clears the value of the "remote_data" field.
func (_u *TaskUpdate) ClearRemoteData() *TaskUpdate {
	_u.mutation.ClearRemoteData()
	return _u
}

// SetLabels sets the "labels" field.
func (_u *TaskUpdate) SetLabels(v []string) *TaskUpdate {
	_u.mutation.SetLabels(v)
	return _u
}

// AppendLabels appends value to the "labels" field.
func (_u *TaskUpdate) AppendLabels(v []string) *TaskUpdate {
	_u.mutation.AppendLabels(v)
	return _u
}

// ClearLabels clears the value of the "labels" field.
func (_u *TaskUpdate) ClearLabels() *TaskUpdate {
	_u.mutation.ClearLabels()
	return _u
}

// SetRepo sets the "repo" field.
func (_u *TaskUpdate) SetRepo(v string) *TaskUpdate {
	_u.mutation.SetRepo(v)
	return _u
}

// SetNillableRepo sets the "repo" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableRepo(v *string) *TaskUpdate {
	if v != nil {
		_u.SetRepo(*v)
	}
	return _u
}

// ClearRepo clears the value of the "repo" field.
func (_u *TaskUpdate) ClearRepo() *TaskUpdate {
	_u.mutation.ClearRepo()
	return _u
}

// SetBranch sets the "branch" field.
func (_u *TaskUpdate) SetBranch(v string) *TaskUpdate {
	_u.mutation.SetBranch(v)
	return _u
}

// SetNillableBranch sets the "branch" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableBranch(v *string) *TaskUpdate {
	if v != nil {
		_u.SetBranch(*v)
	}
	return _u
}

// ClearBranch clears the value of the "branch" field.
func (_u *TaskUpdate) ClearBranch() *TaskUpdate {
	_u.mutation.ClearBranch()
	return _u
}

// SetCiStatus sets the "ci_status" field.
func (_u *TaskUpdate) SetCiStatus(v task.CiStatus) *TaskUpdate {
	_u.mutation.SetCiStatus(v)
	return _u
}

// SetNillableCiStatus sets the "ci_status" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableCiStatus(v *task.CiStatus) *TaskUpdate {
	if v != nil {
		_u.SetCiStatus(*v)
	}
	return _u
}

// ClearCiStatus clears the value of the "ci_status" field.
func (_u *TaskUpdate) ClearCiStatus() *TaskUpdate {
	_u.mutation.ClearCiStatus()
	return _u
}

// SetPullRequests sets the "pull_requests" field.
func (_u *TaskUpdate) SetPullRequests(v []map[string]string) *TaskUpdate {
	_u.mutation.SetPullRequests(v)
	return _u
}

// AppendPullRequests appends value to the "pull_requests" field.
func (_u *TaskUpdate) AppendPullRequests(v []map[string]string) *TaskUpdate {
	_u.mutation.AppendPullRequests(v)
	return _u
}

// ClearPullRequests clears the value of the "pull_requests" field.
func (_u *TaskUpdate) ClearPullRequests() *TaskUpdate {
	_u.mutation.ClearPullRequests()
	return _u
}

// SetVersion sets the "version" field.
func (_u *TaskUpdate) SetVersion(v string) *TaskUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableVersion(v *string) *TaskUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetCollection sets the "collection" edge to the Collection entity.
func (_u *TaskUpdate) SetCollection(v *Collection) *TaskUpdate {
	return _u.SetCollectionID(v.ID)
}

// SetParentID sets the "parent" edge to the Task entity by ID.
func (_u *TaskUpdate) SetParentID(id uuid.UUID) *TaskUpdate {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the Task entity by ID if the given value is not nil.
func (_u *TaskUpdate) SetNillableParentID(id *uuid.UUID) *TaskUpdate {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the Task entity.
func (_u *TaskUpdate) SetParent(v *Task) *TaskUpdate {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Task entity by IDs.
func (_u *TaskUpdate) AddChildIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Task entity.
func (_u *TaskUpdate) AddChildren(v ...*Task) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (_u *TaskUpdate) AddCommentIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.AddCommentIDs(ids...)
	return _u
}

// AddComments adds the "comments" edges to the Comment entity.
func (_u *TaskUpdate) AddComments(v ...*Comment) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommentIDs(ids...)
}

// AddChangeIDs adds the "changes" edge to the Change entity by IDs.
func (_u *TaskUpdate) AddChangeIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.AddChangeIDs(ids...)
	return _u
}

// AddChanges adds the "changes" edges to the Change entity.
func (_u *TaskUpdate) AddChanges(v ...*Change) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChangeIDs(ids...)
}

// AddSourceRelationshipIDs adds the "source_relationships" edge to the Relationship entity by IDs.
func (_u *TaskUpdate) AddSourceRelationshipIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.AddSourceRelationshipIDs(ids...)
	return _u
}

// AddSourceRelationships adds the "source_relationships" edges to the Relationship entity.
func (_u *TaskUpdate) AddSourceRelationships(v ...*Relationship) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSourceRelationshipIDs(ids...)
}

// AddTargetRelationshipIDs adds the "target_relationships" edge to the Relationship entity by IDs.
func (_u *TaskUpdate) AddTargetRelationshipIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.AddTargetRelationshipIDs(ids...)
	return _u
}

// AddTargetRelationships adds the "target_relationships" edges to the Relationship entity.
func (_u *TaskUpdate) AddTargetRelationships(v ...*Relationship) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTargetRelationshipIDs(ids...)
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdate) Mutation() *TaskMutation {
	return _u.mutation
}

// ClearCollection clears the "collection" edge to the Collection entity.
func (_u *TaskUpdate) ClearCollection() *TaskUpdate {
	_u.mutation.ClearCollection()
	return _u
}

// ClearParent clears the "parent" edge to the Task entity.
func (_u *TaskUpdate) ClearParent() *TaskUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the Task entity.
func (_u *TaskUpdate) ClearChildren() *TaskUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Task entities by IDs.
func (_u *TaskUpdate) RemoveChildIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Task entities.
func (_u *TaskUpdate) RemoveChildren(v ...*Task) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearComments clears all "comments" edges to the Comment entity.
func (_u *TaskUpdate) ClearComments() *TaskUpdate {
	_u.mutation.ClearComments()
	return _u
}

// RemoveCommentIDs removes the "comments" edge to Comment entities by IDs.
func (_u *TaskUpdate) RemoveCommentIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.RemoveCommentIDs(ids...)
	return _u
}

// RemoveComments removes "comments" edges to Comment entities.
func (_u *TaskUpdate) RemoveComments(v ...*Comment) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommentIDs(ids...)
}

// ClearChanges clears all "changes" edges to the Change entity.
func (_u *TaskUpdate) ClearChanges() *TaskUpdate {
	_u.mutation.ClearChanges()
	return _u
}

// RemoveChangeIDs removes the "changes" edge to Change entities by IDs.
func (_u *TaskUpdate) RemoveChangeIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.RemoveChangeIDs(ids...)
	return _u
}

// RemoveChanges removes "changes" edges to Change entities.
func (_u *TaskUpdate) RemoveChanges(v ...*Change) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChangeIDs(ids...)
}

// ClearSourceRelationships clears all "source_relationships" edges to the Relationship entity.
func (_u *TaskUpdate) ClearSourceRelationships() *TaskUpdate {
	_u.mutation.ClearSourceRelationships()
	return _u
}

// RemoveSourceRelationshipIDs removes the "source_relationships" edge to Relationship entities by IDs.
func (_u *TaskUpdate) RemoveSourceRelationshipIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.RemoveSourceRelationshipIDs(ids...)
	return _u
}

// RemoveSourceRelationships removes "source_relationships" edges to Relationship entities.
func (_u *TaskUpdate) RemoveSourceRelationships(v ...*Relationship) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSourceRelationshipIDs(ids...)
}

// ClearTargetRelationships clears all "target_relationships" edges to the Relationship entity.
func (_u *TaskUpdate) ClearTargetRelationships() *TaskUpdate {
	_u.mutation.ClearTargetRelationships()
	return _u
}

// RemoveTargetRelationshipIDs removes the "target_relationships" edge to Relationship entities by IDs.
func (_u *TaskUpdate) RemoveTargetRelationshipIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.RemoveTargetRelationshipIDs(ids...)
	return _u
}

// RemoveTargetRelationships removes "target_relationships" edges to Relationship entities.
func (_u *TaskUpdate) RemoveTargetRelationships(v ...*Relationship) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTargetRelationshipIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := task.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := task.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Task.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phase(); ok {
		if err := task.PhaseValidator(v); err != nil {
			return &ValidationError{Name: "phase", err: fmt.Errorf(`ent: validator failed for field "Task.phase": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Stage(); ok {
		if err := task.StageValidator(v); err != nil {
			return &ValidationError{Name: "stage", err: fmt.Errorf(`ent: validator failed for field "Task.stage": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := task.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Task.priority": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CiStatus(); ok {
		if err := task.CiStatusValidator(v); err != nil {
			return &ValidationError{Name: "ci_status", err: fmt.Errorf(`ent: validator failed for field "Task.ci_status": %w`, err)}
		}
	}
	if _u.mutation.CollectionCleared() && len(_u.mutation.CollectionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Task.collection"`)
	}
	return nil
}

func (_u *TaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(task.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(task.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(task.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Phase(); ok {
		_spec.SetField(task.FieldPhase, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Stage(); ok {
		_spec.SetField(task.FieldStage, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.NativeLabel(); ok {
		_spec.SetField(task.FieldNativeLabel, field.TypeString, value)
	}
	if _u.mutation.NativeLabelCleared() {
		_spec.ClearField(task.FieldNativeLabel, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(task.FieldType, field.TypeString, value)
	}
	if _u.mutation.TypeCleared() {
		_spec.ClearField(task.FieldType, field.TypeString)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(task.FieldPriority, field.TypeEnum, value)
	}
	if _u.mutation.PriorityCleared() {
		_spec.ClearField(task.FieldPriority, field.TypeEnum)
	}
	if value, ok := _u.mutation.AssigneeID(); ok {
		_spec.SetField(task.FieldAssigneeID, field.TypeUUID, value)
	}
	if _u.mutation.AssigneeIDCleared() {
		_spec.ClearField(task.FieldAssigneeID, field.TypeUUID)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(task.FieldStartDate, field.TypeTime, value)
	}
	if _u.mutation.StartDateCleared() {
		_spec.ClearField(task.FieldStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.DueDate(); ok {
		_spec.SetField(task.FieldDueDate, field.TypeTime, value)
	}
	if _u.mutation.DueDateCleared() {
		_spec.ClearField(task.FieldDueDate, field.TypeTime)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(task.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(task.FieldClosedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AcceptanceCriteria(); ok {
		_spec.SetField(task.FieldAcceptanceCriteria, field.TypeString, value)
	}
	if _u.mutation.AcceptanceCriteriaCleared() {
		_spec.ClearField(task.FieldAcceptanceCriteria, field.TypeString)
	}
	if value, ok := _u.mutation.RemoteData(); ok {
		_spec.SetField(task.FieldRemoteData, field.TypeJSON, value)
	}
	if _u.mutation.RemoteDataCleared() {
		_spec.ClearField(task.FieldRemoteData, field.TypeJSON)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(task.FieldLabels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLabels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, task.FieldLabels, value)
		})
	}
	if _u.mutation.LabelsCleared() {
		_spec.ClearField(task.FieldLabels, field.TypeJSON)
	}
	if value, ok := _u.mutation.Repo(); ok {
		_spec.SetField(task.FieldRepo, field.TypeString, value)
	}
	if _u.mutation.RepoCleared() {
		_spec.ClearField(task.FieldRepo, field.TypeString)
	}
	if value, ok := _u.mutation.Branch(); ok {
		_spec.SetField(task.FieldBranch, field.TypeString, value)
	}
	if _u.mutation.BranchCleared() {
		_spec.ClearField(task.FieldBranch, field.TypeString)
	}
	if value, ok := _u.mutation.CiStatus(); ok {
		_spec.SetField(task.FieldCiStatus, field.TypeEnum, value)
	}
	if _u.mutation.CiStatusCleared() {
		_spec.ClearField(task.FieldCiStatus, field.TypeEnum)
	}
	if value, ok := _u.mutation.PullRequests(); ok {
		_spec.SetField(task.FieldPullRequests, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPullRequests(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, task.FieldPullRequests, value)
		})
	}
	if _u.mutation.PullRequestsCleared() {
		_spec.ClearField(task.FieldPullRequests, field.TypeJSON)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(task.FieldVersion, field.TypeString, value)
	}
	if _u.mutation.CollectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.CollectionTable,
			Columns: []string{task.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CollectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.CollectionTable,
			Columns: []string{task.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ParentTable,
			Columns: []string{task.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ParentTable,
			Columns: []string{task.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ChildrenTable,
			Columns: []string{task.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ChildrenTable,
			Columns: []string{task.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ChildrenTable,
			Columns: []string{task.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CommentsTable,
			Columns: []string{task.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommentsIDs(); len(nodes) > 0 && !_u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CommentsTable,
			Columns: []string{task.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CommentsTable,
			Columns: []string{task.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChangesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ChangesTable,
			Columns: []string{task.ChangesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(change.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChangesIDs(); len(nodes) > 0 && !_u.mutation.ChangesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ChangesTable,
			Columns: []string{task.ChangesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(change.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChangesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ChangesTable,
			Columns: []string{task.ChangesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(change.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceRelationshipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.SourceRelationshipsTable,
			Columns: []string{task.SourceRelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSourceRelationshipsIDs(); len(nodes) > 0 && !_u.mutation.SourceRelationshipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.SourceRelationshipsTable,
			Columns: []string{task.SourceRelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceRelationshipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.SourceRelationshipsTable,
			Columns: []string{task.SourceRelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TargetRelationshipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.TargetRelationshipsTable,
			Columns: []string{task.TargetRelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTargetRelationshipsIDs(); len(nodes) > 0 && !_u.mutation.TargetRelationshipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.TargetRelationshipsTable,
			Columns: []string{task.TargetRelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetRelationshipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.TargetRelationshipsTable,
			Columns: []string{task.TargetRelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskUpdateOne is the builder for updating a single Task entity.
type TaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskMutation
}

// SetTitle sets the "title" field.
func (_u *TaskUpdateOne) SetTitle(v string) *TaskUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableTitle(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TaskUpdateOne) SetDescription(v string) *TaskUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableDescription(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TaskUpdateOne) ClearDescription() *TaskUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetPhase sets the "phase" field.
func (_u *TaskUpdateOne) SetPhase(v task.Phase) *TaskUpdateOne {
	_u.mutation.SetPhase(v)
	return _u
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillablePhase(v *task.Phase) *TaskUpdateOne {
	if v != nil {
		_u.SetPhase(*v)
	}
	return _u
}

// SetStage sets the "stage" field.
func (_u *TaskUpdateOne) SetStage(v task.Stage) *TaskUpdateOne {
	_u.mutation.SetStage(v)
	return _u
}

// SetNillableStage sets the "stage" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableStage(v *task.Stage) *TaskUpdateOne {
	if v != nil {
		_u.SetStage(*v)
	}
	return _u
}

// SetNativeLabel sets the "native_label" field.
func (_u *TaskUpdateOne) SetNativeLabel(v string) *TaskUpdateOne {
	_u.mutation.SetNativeLabel(v)
	return _u
}

// SetNillableNativeLabel sets the "native_label" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableNativeLabel(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetNativeLabel(*v)
	}
	return _u
}

// ClearNativeLabel clears the value of the "native_label" field.
func (_u *TaskUpdateOne) ClearNativeLabel() *TaskUpdateOne {
	_u.mutation.ClearNativeLabel()
	return _u
}

// SetType sets the "type" field.
func (_u *TaskUpdateOne) SetType(v string) *TaskUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableType(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// ClearType clears the value of the "type" field.
func (_u *TaskUpdateOne) ClearType() *TaskUpdateOne {
	_u.mutation.ClearType()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TaskUpdateOne) SetPriority(v task.Priority) *TaskUpdateOne {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillablePriority(v *task.Priority) *TaskUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// ClearPriority clears the value of the "priority" field.
func (_u *TaskUpdateOne) ClearPriority() *TaskUpdateOne {
	_u.mutation.ClearPriority()
	return _u
}

// SetAssigneeID sets the "assignee_id" field.
func (_u *TaskUpdateOne) SetAssigneeID(v uuid.UUID) *TaskUpdateOne {
	_u.mutation.SetAssigneeID(v)
	return _u
}

// SetNillableAssigneeID sets the "assignee_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableAssigneeID(v *uuid.UUID) *TaskUpdateOne {
	if v != nil {
		_u.SetAssigneeID(*v)
	}
	return _u
}

// ClearAssigneeID clears the value of the "assignee_id" field.
func (_u *TaskUpdateOne) ClearAssigneeID() *TaskUpdateOne {
	_u.mutation.ClearAssigneeID()
	return _u
}

// SetCollectionID sets the "collection_id" field.
func (_u *TaskUpdateOne) SetCollectionID(v uuid.UUID) *TaskUpdateOne {
	_u.mutation.SetCollectionID(v)
	return _u
}

// SetNillableCollectionID sets the "collection_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableCollectionID(v *uuid.UUID) *TaskUpdateOne {
	if v != nil {
		_u.SetCollectionID(*v)
	}
	return _u
}

// SetParentTaskID sets the "parent_task_id" field.
func (_u *TaskUpdateOne) SetParentTaskID(v uuid.UUID) *TaskUpdateOne {
	_u.mutation.SetParentTaskID(v)
	return _u
}

// SetNillableParentTaskID sets the "parent_task_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableParentTaskID(v *uuid.UUID) *TaskUpdateOne {
	if v != nil {
		_u.SetParentTaskID(*v)
	}
	return _u
}

// ClearParentTaskID clears the value of the "parent_task_id" field.
func (_u *TaskUpdateOne) ClearParentTaskID() *TaskUpdateOne {
	_u.mutation.ClearParentTaskID()
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *TaskUpdateOne) SetStartDate(v time.Time) *TaskUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableStartDate(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// ClearStartDate clears the value of the "start_date" field.
func (_u *TaskUpdateOne) ClearStartDate() *TaskUpdateOne {
	_u.mutation.ClearStartDate()
	return _u
}

// SetDueDate sets the "due_date" field.
func (_u *TaskUpdateOne) SetDueDate(v time.Time) *TaskUpdateOne {
	_u.mutation.SetDueDate(v)
	return _u
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableDueDate(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetDueDate(*v)
	}
	return _u
}

// ClearDueDate clears the value of the "due_date" field.
func (_u *TaskUpdateOne) ClearDueDate() *TaskUpdateOne {
	_u.mutation.ClearDueDate()
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *TaskUpdateOne) SetClosedAt(v time.Time) *TaskUpdateOne {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableClosedAt(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *TaskUpdateOne) ClearClosedAt() *TaskUpdateOne {
	_u.mutation.ClearClosedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskUpdateOne) SetUpdatedAt(v time.Time) *TaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAcceptanceCriteria sets the "acceptance_criteria" field.
func (_u *TaskUpdateOne) SetAcceptanceCriteria(v string) *TaskUpdateOne {
	_u.mutation.SetAcceptanceCriteria(v)
	return _u
}

// SetNillableAcceptanceCriteria sets the "acceptance_criteria" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableAcceptanceCriteria(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetAcceptanceCriteria(*v)
	}
	return _u
}

// ClearAcceptanceCriteria clears the value of the "acceptance_criteria" field.
func (_u *TaskUpdateOne) ClearAcceptanceCriteria() *TaskUpdateOne {
	_u.mutation.ClearAcceptanceCriteria()
	return _u
}

// SetRemoteData sets the "remote_data" field.
func (_u *TaskUpdateOne) SetRemoteData(v map[string]interface{}) *TaskUpdateOne {
	_u.mutation.SetRemoteData(v)
	return _u
}

// ClearRemoteData clears the value of the "remote_data" field.
func (_u *TaskUpdateOne) ClearRemoteData() *TaskUpdateOne {
	_u.mutation.ClearRemoteData()
	return _u
}

// SetLabels sets the "labels" field.
func (_u *TaskUpdateOne) SetLabels(v []string) *TaskUpdateOne {
	_u.mutation.SetLabels(v)
	return _u
}

// AppendLabels appends value to the "labels" field.
func (_u *TaskUpdateOne) AppendLabels(v []string) *TaskUpdateOne {
	_u.mutation.AppendLabels(v)
	return _u
}

// ClearLabels clears the value of the "labels" field.
func (_u *TaskUpdateOne) ClearLabels() *TaskUpdateOne {
	_u.mutation.ClearLabels()
	return _u
}

// SetRepo sets the "repo" field.
func (_u *TaskUpdateOne) SetRepo(v string) *TaskUpdateOne {
	_u.mutation.SetRepo(v)
	return _u
}

// SetNillableRepo sets the "repo" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableRepo(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetRepo(*v)
	}
	return _u
}

// ClearRepo clears the value of the "repo" field.
func (_u *TaskUpdateOne) ClearRepo() *TaskUpdateOne {
	_u.mutation.ClearRepo()
	return _u
}

// SetBranch sets the "branch" field.
func (_u *TaskUpdateOne) SetBranch(v string) *TaskUpdateOne {
	_u.mutation.SetBranch(v)
	return _u
}

// SetNillableBranch sets the "branch" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableBranch(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetBranch(*v)
	}
	return _u
}

// ClearBranch clears the value of the "branch" field.
func (_u *TaskUpdateOne) ClearBranch() *TaskUpdateOne {
	_u.mutation.ClearBranch()
	return _u
}

// SetCiStatus sets the "ci_status" field.
func (_u *TaskUpdateOne) SetCiStatus(v task.CiStatus) *TaskUpdateOne {
	_u.mutation.SetCiStatus(v)
	return _u
}

// SetNillableCiStatus sets the "ci_status" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableCiStatus(v *task.CiStatus) *TaskUpdateOne {
	if v != nil {
		_u.SetCiStatus(*v)
	}
	return _u
}

// ClearCiStatus clears the value of the "ci_status" field.
func (_u *TaskUpdateOne) ClearCiStatus() *TaskUpdateOne {
	_u.mutation.ClearCiStatus()
	return _u
}

// SetPullRequests sets the "pull_requests" field.
func (_u *TaskUpdateOne) SetPullRequests(v []map[string]string) *TaskUpdateOne {
	_u.mutation.SetPullRequests(v)
	return _u
}

// AppendPullRequests appends value to the "pull_requests" field.
func (_u *TaskUpdateOne) AppendPullRequests(v []map[string]string) *TaskUpdateOne {
	_u.mutation.AppendPullRequests(v)
	return _u
}

// ClearPullRequests clears the value of the "pull_requests" field.
func (_u *TaskUpdateOne) ClearPullRequests() *TaskUpdateOne {
	_u.mutation.ClearPullRequests()
	return _u
}

// SetVersion sets the "version" field.
func (_u *TaskUpdateOne) SetVersion(v string) *TaskUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableVersion(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetCollection sets the "collection" edge to the Collection entity.
func (_u *TaskUpdateOne) SetCollection(v *Collection) *TaskUpdateOne {
	return _u.SetCollectionID(v.ID)
}

// SetParentID sets the "parent" edge to the Task entity by ID.
func (_u *TaskUpdateOne) SetParentID(id uuid.UUID) *TaskUpdateOne {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the Task entity by ID if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableParentID(id *uuid.UUID) *TaskUpdateOne {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the Task entity.
func (_u *TaskUpdateOne) SetParent(v *Task) *TaskUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Task entity by IDs.
func (_u *TaskUpdateOne) AddChildIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Task entity.
func (_u *TaskUpdateOne) AddChildren(v ...*Task) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (_u *TaskUpdateOne) AddCommentIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.AddCommentIDs(ids...)
	return _u
}

// AddComments adds the "comments" edges to the Comment entity.
func (_u *TaskUpdateOne) AddComments(v ...*Comment) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommentIDs(ids...)
}

// AddChangeIDs adds the "changes" edge to the Change entity by IDs.
func (_u *TaskUpdateOne) AddChangeIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.AddChangeIDs(ids...)
	return _u
}

// AddChanges adds the "changes" edges to the Change entity.
func (_u *TaskUpdateOne) AddChanges(v ...*Change) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChangeIDs(ids...)
}

// AddSourceRelationshipIDs adds the "source_relationships" edge to the Relationship entity by IDs.
func (_u *TaskUpdateOne) AddSourceRelationshipIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.AddSourceRelationshipIDs(ids...)
	return _u
}

// AddSourceRelationships adds the "source_relationships" edges to the Relationship entity.
func (_u *TaskUpdateOne) AddSourceRelationships(v ...*Relationship) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSourceRelationshipIDs(ids...)
}

// AddTargetRelationshipIDs adds the "target_relationships" edge to the Relationship entity by IDs.
func (_u *TaskUpdateOne) AddTargetRelationshipIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.AddTargetRelationshipIDs(ids...)
	return _u
}

// AddTargetRelationships adds the "target_relationships" edges to the Relationship entity.
func (_u *TaskUpdateOne) AddTargetRelationships(v ...*Relationship) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTargetRelationshipIDs(ids...)
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdateOne) Mutation() *TaskMutation {
	return _u.mutation
}

// ClearCollection clears the "collection" edge to the Collection entity.
func (_u *TaskUpdateOne) ClearCollection() *TaskUpdateOne {
	_u.mutation.ClearCollection()
	return _u
}

// ClearParent clears the "parent" edge to the Task entity.
func (_u *TaskUpdateOne) ClearParent() *TaskUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the Task entity.
func (_u *TaskUpdateOne) ClearChildren() *TaskUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Task entities by IDs.
func (_u *TaskUpdateOne) RemoveChildIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Task entities.
func (_u *TaskUpdateOne) RemoveChildren(v ...*Task) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearComments clears all "comments" edges to the Comment entity.
func (_u *TaskUpdateOne) ClearComments() *TaskUpdateOne {
	_u.mutation.ClearComments()
	return _u
}

// RemoveCommentIDs removes the "comments" edge to Comment entities by IDs.
func (_u *TaskUpdateOne) RemoveCommentIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.RemoveCommentIDs(ids...)
	return _u
}

// RemoveComments removes "comments" edges to Comment entities.
func (_u *TaskUpdateOne) RemoveComments(v ...*Comment) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommentIDs(ids...)
}

// ClearChanges clears all "changes" edges to the Change entity.
func (_u *TaskUpdateOne) ClearChanges() *TaskUpdateOne {
	_u.mutation.ClearChanges()
	return _u
}

// RemoveChangeIDs removes the "changes" edge to Change entities by IDs.
func (_u *TaskUpdateOne) RemoveChangeIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.RemoveChangeIDs(ids...)
	return _u
}

// RemoveChanges removes "changes" edges to Change entities.
func (_u *TaskUpdateOne) RemoveChanges(v ...*Change) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChangeIDs(ids...)
}

// ClearSourceRelationships clears all "source_relationships" edges to the Relationship entity.
func (_u *TaskUpdateOne) ClearSourceRelationships() *TaskUpdateOne {
	_u.mutation.ClearSourceRelationships()
	return _u
}

// RemoveSourceRelationshipIDs removes the "source_relationships" edge to Relationship entities by IDs.
func (_u *TaskUpdateOne) RemoveSourceRelationshipIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.RemoveSourceRelationshipIDs(ids...)
	return _u
}

// RemoveSourceRelationships removes "source_relationships" edges to Relationship entities.
func (_u *TaskUpdateOne) RemoveSourceRelationships(v ...*Relationship) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSourceRelationshipIDs(ids...)
}

// ClearTargetRelationships clears all "target_relationships" edges to the Relationship entity.
func (_u *TaskUpdateOne) ClearTargetRelationships() *TaskUpdateOne {
	_u.mutation.ClearTargetRelationships()
	return _u
}

// RemoveTargetRelationshipIDs removes the "target_relationships" edge to Relationship entities by IDs.
func (_u *TaskUpdateOne) RemoveTargetRelationshipIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.RemoveTargetRelationshipIDs(ids...)
	return _u
}

// RemoveTargetRelationships removes "target_relationships" edges to Relationship entities.
func (_u *TaskUpdateOne) RemoveTargetRelationships(v ...*Relationship) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTargetRelationshipIDs(ids...)
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdateOne) Where(ps ...predicate.Task) *TaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskUpdateOne) Select(field string, fields ...string) *TaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Task entity.
func (_u *TaskUpdateOne) Save(ctx context.Context) (*Task, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdateOne) SaveX(ctx context.Context) *Task {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := task.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := task.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Task.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phase(); ok {
		if err := task.PhaseValidator(v); err != nil {
			return &ValidationError{Name: "phase", err: fmt.Errorf(`ent: validator failed for field "Task.phase": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Stage(); ok {
		if err := task.StageValidator(v); err != nil {
			return &ValidationError{Name: "stage", err: fmt.Errorf(`ent: validator failed for field "Task.stage": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := task.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Task.priority": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CiStatus(); ok {
		if err := task.CiStatusValidator(v); err != nil {
			return &ValidationError{Name: "ci_status", err: fmt.Errorf(`ent: validator failed for field "Task.ci_status": %w`, err)}
		}
	}
	if _u.mutation.CollectionCleared() && len(_u.mutation.CollectionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Task.collection"`)
	}
	return nil
}

func (_u *TaskUpdateOne) sqlSave(ctx context.Context) (_node *Task, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Task.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, task.FieldID)
		for _, f := range fields {
			if !task.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != task.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(task.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(task.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(task.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Phase(); ok {
		_spec.SetField(task.FieldPhase, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Stage(); ok {
		_spec.SetField(task.FieldStage, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.NativeLabel(); ok {
		_spec.SetField(task.FieldNativeLabel, field.TypeString, value)
	}
	if _u.mutation.NativeLabelCleared() {
		_spec.ClearField(task.FieldNativeLabel, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(task.FieldType, field.TypeString, value)
	}
	if _u.mutation.TypeCleared() {
		_spec.ClearField(task.FieldType, field.TypeString)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(task.FieldPriority, field.TypeEnum, value)
	}
	if _u.mutation.PriorityCleared() {
		_spec.ClearField(task.FieldPriority, field.TypeEnum)
	}
	if value, ok := _u.mutation.AssigneeID(); ok {
		_spec.SetField(task.FieldAssigneeID, field.TypeUUID, value)
	}
	if _u.mutation.AssigneeIDCleared() {
		_spec.ClearField(task.FieldAssigneeID, field.TypeUUID)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(task.FieldStartDate, field.TypeTime, value)
	}
	if _u.mutation.StartDateCleared() {
		_spec.ClearField(task.FieldStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.DueDate(); ok {
		_spec.SetField(task.FieldDueDate, field.TypeTime, value)
	}
	if _u.mutation.DueDateCleared() {
		_spec.ClearField(task.FieldDueDate, field.TypeTime)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(task.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(task.FieldClosedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AcceptanceCriteria(); ok {
		_spec.SetField(task.FieldAcceptanceCriteria, field.TypeString, value)
	}
	if _u.mutation.AcceptanceCriteriaCleared() {
		_spec.ClearField(task.FieldAcceptanceCriteria, field.TypeString)
	}
	if value, ok := _u.mutation.RemoteData(); ok {
		_spec.SetField(task.FieldRemoteData, field.TypeJSON, value)
	}
	if _u.mutation.RemoteDataCleared() {
		_spec.ClearField(task.FieldRemoteData, field.TypeJSON)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(task.FieldLabels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLabels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, task.FieldLabels, value)
		})
	}
	if _u.mutation.LabelsCleared() {
		_spec.ClearField(task.FieldLabels, field.TypeJSON)
	}
	if value, ok := _u.mutation.Repo(); ok {
		_spec.SetField(task.FieldRepo, field.TypeString, value)
	}
	if _u.mutation.RepoCleared() {
		_spec.ClearField(task.FieldRepo, field.TypeString)
	}
	if value, ok := _u.mutation.Branch(); ok {
		_spec.SetField(task.FieldBranch, field.TypeString, value)
	}
	if _u.mutation.BranchCleared() {
		_spec.ClearField(task.FieldBranch, field.TypeString)
	}
	if value, ok := _u.mutation.CiStatus(); ok {
		_spec.SetField(task.FieldCiStatus, field.TypeEnum, value)
	}
	if _u.mutation.CiStatusCleared() {
		_spec.ClearField(task.FieldCiStatus, field.TypeEnum)
	}
	if value, ok := _u.mutation.PullRequests(); ok {
		_spec.SetField(task.FieldPullRequests, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPullRequests(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, task.FieldPullRequests, value)
		})
	}
	if _u.mutation.PullRequestsCleared() {
		_spec.ClearField(task.FieldPullRequests, field.TypeJSON)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(task.FieldVersion, field.TypeString, value)
	}
	if _u.mutation.CollectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.CollectionTable,
			Columns: []string{task.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CollectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.CollectionTable,
			Columns: []string{task.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ParentTable,
			Columns: []string{task.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ParentTable,
			Columns: []string{task.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ChildrenTable,
			Columns: []string{task.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ChildrenTable,
			Columns: []string{task.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ChildrenTable,
			Columns: []string{task.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CommentsTable,
			Columns: []string{task.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommentsIDs(); len(nodes) > 0 && !_u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CommentsTable,
			Columns: []string{task.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CommentsTable,
			Columns: []string{task.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChangesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ChangesTable,
			Columns: []string{task.ChangesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(change.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChangesIDs(); len(nodes) > 0 && !_u.mutation.ChangesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ChangesTable,
			Columns: []string{task.ChangesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(change.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChangesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ChangesTable,
			Columns: []string{task.ChangesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(change.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceRelationshipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.SourceRelationshipsTable,
			Columns: []string{task.SourceRelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSourceRelationshipsIDs(); len(nodes) > 0 && !_u.mutation.SourceRelationshipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.SourceRelationshipsTable,
			Columns: []string{task.SourceRelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceRelationshipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.SourceRelationshipsTable,
			Columns: []string{task.SourceRelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TargetRelationshipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.TargetRelationshipsTable,
			Columns: []string{task.TargetRelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTargetRelationshipsIDs(); len(nodes) > 0 && !_u.mutation.TargetRelationshipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.TargetRelationshipsTable,
			Columns: []string{task.TargetRelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetRelationshipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.TargetRelationshipsTable,
			Columns: []string{task.TargetRelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Task{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
