// Code generated by ent, DO NOT EDIT.

package linkedaccount

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the linkedaccount type in the database.
	Label = "linked_account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCollectionID holds the string denoting the collection_id field in the database.
	FieldCollectionID = "collection_id"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldAuthToken holds the string denoting the auth_token field in the database.
	FieldAuthToken = "auth_token"
	// FieldAuthMethod holds the string denoting the auth_method field in the database.
	FieldAuthMethod = "auth_method"
	// FieldScopes holds the string denoting the scopes field in the database.
	FieldScopes = "scopes"
	// FieldRemoteUserID holds the string denoting the remote_user_id field in the database.
	FieldRemoteUserID = "remote_user_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// EdgeCollection holds the string denoting the collection edge name in mutations.
	EdgeCollection = "collection"
	// Table holds the table name of the linkedaccount in the database.
	Table = "linked_accounts"
	// CollectionTable is the table that holds the collection relation/edge.
	CollectionTable = "linked_accounts"
	// CollectionInverseTable is the table name for the Collection entity.
	// It exists in this package in order to avoid circular dependency with the "collection" package.
	CollectionInverseTable = "collections"
	// CollectionColumn is the table column denoting the collection relation/edge.
	CollectionColumn = "collection_id"
)

// Columns holds all SQL columns for linkedaccount fields.
var Columns = []string{
	FieldID,
	FieldCollectionID,
	FieldPlatform,
	FieldAuthToken,
	FieldAuthMethod,
	FieldScopes,
	FieldRemoteUserID,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRemoteUserID holds the default value on creation for the "remote_user_id" field.
	DefaultRemoteUserID string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Platform defines the type for the "platform" enum field.
type Platform string

// Platform values.
const (
	PlatformGithub Platform = "github"
	PlatformLinear Platform = "linear"
	PlatformJira   Platform = "jira"
	PlatformAsana  Platform = "asana"
	PlatformBeads  Platform = "beads"
)

func (pl Platform) String() string {
	return string(pl)
}

// PlatformValidator is a validator for the "platform" field enum values. It is called by the builders before save.
func PlatformValidator(pl Platform) error {
	switch pl {
	case PlatformGithub, PlatformLinear, PlatformJira, PlatformAsana, PlatformBeads:
		return nil
	default:
		return fmt.Errorf("linkedaccount: invalid enum value for platform field: %q", pl)
	}
}

// AuthMethod defines the type for the "auth_method" enum field.
type AuthMethod string

// AuthMethod values.
const (
	AuthMethodPat       AuthMethod = "pat"
	AuthMethodOauth     AuthMethod = "oauth"
	AuthMethodGithubApp AuthMethod = "github_app"
)

func (am AuthMethod) String() string {
	return string(am)
}

// AuthMethodValidator is a validator for the "auth_method" field enum values. It is called by the builders before save.
func AuthMethodValidator(am AuthMethod) error {
	switch am {
	case AuthMethodPat, AuthMethodOauth, AuthMethodGithubApp:
		return nil
	default:
		return fmt.Errorf("linkedaccount: invalid enum value for auth_method field: %q", am)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive  Status = "active"
	StatusExpired Status = "expired"
	StatusRevoked Status = "revoked"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusExpired, StatusRevoked:
		return nil
	default:
		return fmt.Errorf("linkedaccount: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the LinkedAccount queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCollectionID orders the results by the collection_id field.
func ByCollectionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCollectionID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByAuthToken orders the results by the auth_token field.
func ByAuthToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthToken, opts...).ToFunc()
}

// ByAuthMethod orders the results by the auth_method field.
func ByAuthMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthMethod, opts...).ToFunc()
}

// ByRemoteUserID orders the results by the remote_user_id field.
func ByRemoteUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemoteUserID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByCollectionField orders the results by collection field.
func ByCollectionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCollectionStep(), sql.OrderByField(field, opts...))
	}
}
func newCollectionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CollectionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CollectionTable, CollectionColumn),
	)
}
