// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APITokensColumns holds the columns for the "api_tokens" table.
	APITokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// APITokensTable holds the schema information for the "api_tokens" table.
	APITokensTable = &schema.Table{
		Name:       "api_tokens",
		Columns:    APITokensColumns,
		PrimaryKey: []*schema.Column{APITokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "api_tokens_users_api_tokens",
				Columns:    []*schema.Column{APITokensColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "apitoken_token_hash",
				Unique:  true,
				Columns: []*schema.Column{APITokensColumns[1]},
			},
			{
				Name:    "apitoken_user_id",
				Unique:  false,
				Columns: []*schema.Column{APITokensColumns[6]},
			},
		},
	}
	// ChangesColumns holds the columns for the "changes" table.
	ChangesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "author_id", Type: field.TypeUUID},
		{Name: "field_name", Type: field.TypeString},
		{Name: "old_value", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "new_value", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "task_id", Type: field.TypeUUID},
	}
	// ChangesTable holds the schema information for the "changes" table.
	ChangesTable = &schema.Table{
		Name:       "changes",
		Columns:    ChangesColumns,
		PrimaryKey: []*schema.Column{ChangesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "changes_tasks_changes",
				Columns:    []*schema.Column{ChangesColumns[6]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "change_task_id",
				Unique:  false,
				Columns: []*schema.Column{ChangesColumns[6]},
			},
		},
	}
	// CollectionsColumns holds the columns for the "collections" table.
	CollectionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "platform", Type: field.TypeEnum, Enums: []string{"farmtable", "github", "linear", "jira", "asana", "beads"}, Default: "farmtable"},
		{Name: "remote_id", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CollectionsTable holds the schema information for the "collections" table.
	CollectionsTable = &schema.Table{
		Name:       "collections",
		Columns:    CollectionsColumns,
		PrimaryKey: []*schema.Column{CollectionsColumns[0]},
	}
	// CommentsColumns holds the columns for the "comments" table.
	CommentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "author_id", Type: field.TypeUUID},
		{Name: "body", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "task_id", Type: field.TypeUUID},
	}
	// CommentsTable holds the schema information for the "comments" table.
	CommentsTable = &schema.Table{
		Name:       "comments",
		Columns:    CommentsColumns,
		PrimaryKey: []*schema.Column{CommentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "comments_tasks_comments",
				Columns:    []*schema.Column{CommentsColumns[5]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "comment_task_id",
				Unique:  false,
				Columns: []*schema.Column{CommentsColumns[5]},
			},
		},
	}
	// RelationshipsColumns holds the columns for the "relationships" table.
	RelationshipsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"blocks", "blocked_by", "relates_to", "duplicates", "duplicated_by"}},
		{Name: "source_task_id", Type: field.TypeUUID},
		{Name: "target_task_id", Type: field.TypeUUID},
	}
	// RelationshipsTable holds the schema information for the "relationships" table.
	RelationshipsTable = &schema.Table{
		Name:       "relationships",
		Columns:    RelationshipsColumns,
		PrimaryKey: []*schema.Column{RelationshipsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "relationships_tasks_source_relationships",
				Columns:    []*schema.Column{RelationshipsColumns[2]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "relationships_tasks_target_relationships",
				Columns:    []*schema.Column{RelationshipsColumns[3]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "relationship_source_task_id",
				Unique:  false,
				Columns: []*schema.Column{RelationshipsColumns[2]},
			},
			{
				Name:    "relationship_target_task_id",
				Unique:  false,
				Columns: []*schema.Column{RelationshipsColumns[3]},
			},
			{
				Name:    "relationship_source_task_id_target_task_id_type",
				Unique:  true,
				Columns: []*schema.Column{RelationshipsColumns[2], RelationshipsColumns[3], RelationshipsColumns[1]},
			},
		},
	}
	// TasksColumns holds the columns for the "tasks" table.
	TasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "phase", Type: field.TypeEnum, Enums: []string{"open", "in_progress", "on_hold", "closed"}, Default: "open"},
		{Name: "stage", Type: field.TypeEnum, Enums: []string{"triage", "backlog", "ready", "working", "in_review", "in_qa", "deploying", "blocked", "waiting_for_input", "deferred", "scheduled", "completed", "wont_fix", "duplicate", "cancelled"}, Default: "triage"},
		{Name: "native_label", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "type", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "priority", Type: field.TypeEnum, Nullable: true, Enums: []string{"urgent", "high", "normal", "low"}},
		{Name: "assignee_id", Type: field.TypeUUID, Nullable: true},
		{Name: "start_date", Type: field.TypeTime, Nullable: true},
		{Name: "due_date", Type: field.TypeTime, Nullable: true},
		{Name: "closed_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "acceptance_criteria", Type: field.TypeString, Nullable: true},
		{Name: "remote_data", Type: field.TypeJSON, Nullable: true},
		{Name: "labels", Type: field.TypeJSON, Nullable: true},
		{Name: "repo", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "branch", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "ci_status", Type: field.TypeEnum, Nullable: true, Enums: []string{"unknown", "pending", "running", "passed", "failed"}},
		{Name: "pull_requests", Type: field.TypeJSON, Nullable: true},
		{Name: "version", Type: field.TypeString, Default: "1"},
		{Name: "collection_id", Type: field.TypeUUID},
		{Name: "parent_task_id", Type: field.TypeUUID, Nullable: true},
	}
	// TasksTable holds the schema information for the "tasks" table.
	TasksTable = &schema.Table{
		Name:       "tasks",
		Columns:    TasksColumns,
		PrimaryKey: []*schema.Column{TasksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tasks_collections_tasks",
				Columns:    []*schema.Column{TasksColumns[22]},
				RefColumns: []*schema.Column{CollectionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "tasks_tasks_children",
				Columns:    []*schema.Column{TasksColumns[23]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "task_id_version",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[0], TasksColumns[21]},
			},
			{
				Name:    "task_collection_id",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[22]},
			},
			{
				Name:    "task_phase",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[3]},
			},
			{
				Name:    "task_assignee_id",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[8]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "display_name", Type: field.TypeString},
		{Name: "type", Type: field.TypeString, Default: "agent"},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "platform_id", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APITokensTable,
		ChangesTable,
		CollectionsTable,
		CommentsTable,
		RelationshipsTable,
		TasksTable,
		UsersTable,
	}
)

func init() {
	APITokensTable.ForeignKeys[0].RefTable = UsersTable
	ChangesTable.ForeignKeys[0].RefTable = TasksTable
	CommentsTable.ForeignKeys[0].RefTable = TasksTable
	RelationshipsTable.ForeignKeys[0].RefTable = TasksTable
	RelationshipsTable.ForeignKeys[1].RefTable = TasksTable
	TasksTable.ForeignKeys[0].RefTable = CollectionsTable
	TasksTable.ForeignKeys[1].RefTable = TasksTable
}
