// Code generated by ent, DO NOT EDIT.

package task

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/farmtable-io/farmtable/internal/store/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldDescription, v))
}

// NativeLabel applies equality check predicate on the "native_label" field. It's identical to NativeLabelEQ.
func NativeLabel(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldNativeLabel, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldType, v))
}

// AssigneeID applies equality check predicate on the "assignee_id" field. It's identical to AssigneeIDEQ.
func AssigneeID(v uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldAssigneeID, v))
}

// CollectionID applies equality check predicate on the "collection_id" field. It's identical to CollectionIDEQ.
func CollectionID(v uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCollectionID, v))
}

// ParentTaskID applies equality check predicate on the "parent_task_id" field. It's identical to ParentTaskIDEQ.
func ParentTaskID(v uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldParentTaskID, v))
}

// StartDate applies equality check predicate on the "start_date" field. It's identical to StartDateEQ.
func StartDate(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldStartDate, v))
}

// DueDate applies equality check predicate on the "due_date" field. It's identical to DueDateEQ.
func DueDate(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldDueDate, v))
}

// ClosedAt applies equality check predicate on the "closed_at" field. It's identical to ClosedAtEQ.
func ClosedAt(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldClosedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldUpdatedAt, v))
}

// AcceptanceCriteria applies equality check predicate on the "acceptance_criteria" field. It's identical to AcceptanceCriteriaEQ.
func AcceptanceCriteria(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldAcceptanceCriteria, v))
}

// Repo applies equality check predicate on the "repo" field. It's identical to RepoEQ.
func Repo(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldRepo, v))
}

// Branch applies equality check predicate on the "branch" field. It's identical to BranchEQ.
func Branch(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldBranch, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldVersion, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldDescription, v))
}

// PhaseEQ applies the EQ predicate on the "phase" field.
func PhaseEQ(v Phase) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldPhase, v))
}

// PhaseNEQ applies the NEQ predicate on the "phase" field.
func PhaseNEQ(v Phase) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldPhase, v))
}

// PhaseIn applies the In predicate on the "phase" field.
func PhaseIn(vs ...Phase) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldPhase, vs...))
}

// PhaseNotIn applies the NotIn predicate on the "phase" field.
func PhaseNotIn(vs ...Phase) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldPhase, vs...))
}

// StageEQ applies the EQ predicate on the "stage" field.
func StageEQ(v Stage) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldStage, v))
}

// StageNEQ applies the NEQ predicate on the "stage" field.
func StageNEQ(v Stage) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldStage, v))
}

// StageIn applies the In predicate on the "stage" field.
func StageIn(vs ...Stage) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldStage, vs...))
}

// StageNotIn applies the NotIn predicate on the "stage" field.
func StageNotIn(vs ...Stage) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldStage, vs...))
}

// NativeLabelEQ applies the EQ predicate on the "native_label" field.
func NativeLabelEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldNativeLabel, v))
}

// NativeLabelNEQ applies the NEQ predicate on the "native_label" field.
func NativeLabelNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldNativeLabel, v))
}

// NativeLabelIn applies the In predicate on the "native_label" field.
func NativeLabelIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldNativeLabel, vs...))
}

// NativeLabelNotIn applies the NotIn predicate on the "native_label" field.
func NativeLabelNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldNativeLabel, vs...))
}

// NativeLabelGT applies the GT predicate on the "native_label" field.
func NativeLabelGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldNativeLabel, v))
}

// NativeLabelGTE applies the GTE predicate on the "native_label" field.
func NativeLabelGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldNativeLabel, v))
}

// NativeLabelLT applies the LT predicate on the "native_label" field.
func NativeLabelLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldNativeLabel, v))
}

// NativeLabelLTE applies the LTE predicate on the "native_label" field.
func NativeLabelLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldNativeLabel, v))
}

// NativeLabelContains applies the Contains predicate on the "native_label" field.
func NativeLabelContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldNativeLabel, v))
}

// NativeLabelHasPrefix applies the HasPrefix predicate on the "native_label" field.
func NativeLabelHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldNativeLabel, v))
}

// NativeLabelHasSuffix applies the HasSuffix predicate on the "native_label" field.
func NativeLabelHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldNativeLabel, v))
}

// NativeLabelIsNil applies the IsNil predicate on the "native_label" field.
func NativeLabelIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldNativeLabel))
}

// NativeLabelNotNil applies the NotNil predicate on the "native_label" field.
func NativeLabelNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldNativeLabel))
}

// NativeLabelEqualFold applies the EqualFold predicate on the "native_label" field.
func NativeLabelEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldNativeLabel, v))
}

// NativeLabelContainsFold applies the ContainsFold predicate on the "native_label" field.
func NativeLabelContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldNativeLabel, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldType, v))
}

// TypeIsNil applies the IsNil predicate on the "type" field.
func TypeIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldType))
}

// TypeNotNil applies the NotNil predicate on the "type" field.
func TypeNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldType))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldType, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v Priority) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v Priority) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...Priority) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...Priority) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityIsNil applies the IsNil predicate on the "priority" field.
func PriorityIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldPriority))
}

// PriorityNotNil applies the NotNil predicate on the "priority" field.
func PriorityNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldPriority))
}

// AssigneeIDEQ applies the EQ predicate on the "assignee_id" field.
func AssigneeIDEQ(v uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldAssigneeID, v))
}

// AssigneeIDNEQ applies the NEQ predicate on the "assignee_id" field.
func AssigneeIDNEQ(v uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldAssigneeID, v))
}

// AssigneeIDIn applies the In predicate on the "assignee_id" field.
func AssigneeIDIn(vs ...uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldAssigneeID, vs...))
}

// AssigneeIDNotIn applies the NotIn predicate on the "assignee_id" field.
func AssigneeIDNotIn(vs ...uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldAssigneeID, vs...))
}

// AssigneeIDGT applies the GT predicate on the "assignee_id" field.
func AssigneeIDGT(v uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldAssigneeID, v))
}

// AssigneeIDGTE applies the GTE predicate on the "assignee_id" field.
func AssigneeIDGTE(v uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldAssigneeID, v))
}

// AssigneeIDLT applies the LT predicate on the "assignee_id" field.
func AssigneeIDLT(v uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldAssigneeID, v))
}

// AssigneeIDLTE applies the LTE predicate on the "assignee_id" field.
func AssigneeIDLTE(v uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldAssigneeID, v))
}

// AssigneeIDIsNil applies the IsNil predicate on the "assignee_id" field.
func AssigneeIDIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldAssigneeID))
}

// AssigneeIDNotNil applies the NotNil predicate on the "assignee_id" field.
func AssigneeIDNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldAssigneeID))
}

// CollectionIDEQ applies the EQ predicate on the "collection_id" field.
func CollectionIDEQ(v uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCollectionID, v))
}

// CollectionIDNEQ applies the NEQ predicate on the "collection_id" field.
func CollectionIDNEQ(v uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldCollectionID, v))
}

// CollectionIDIn applies the In predicate on the "collection_id" field.
func CollectionIDIn(vs ...uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldCollectionID, vs...))
}

// CollectionIDNotIn applies the NotIn predicate on the "collection_id" field.
func CollectionIDNotIn(vs ...uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldCollectionID, vs...))
}

// ParentTaskIDEQ applies the EQ predicate on the "parent_task_id" field.
func ParentTaskIDEQ(v uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldParentTaskID, v))
}

// ParentTaskIDNEQ applies the NEQ predicate on the "parent_task_id" field.
func ParentTaskIDNEQ(v uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldParentTaskID, v))
}

// ParentTaskIDIn applies the In predicate on the "parent_task_id" field.
func ParentTaskIDIn(vs ...uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldParentTaskID, vs...))
}

// ParentTaskIDNotIn applies the NotIn predicate on the "parent_task_id" field.
func ParentTaskIDNotIn(vs ...uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldParentTaskID, vs...))
}

// ParentTaskIDIsNil applies the IsNil predicate on the "parent_task_id" field.
func ParentTaskIDIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldParentTaskID))
}

// ParentTaskIDNotNil applies the NotNil predicate on the "parent_task_id" field.
func ParentTaskIDNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldParentTaskID))
}

// StartDateEQ applies the EQ predicate on the "start_date" field.
func StartDateEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldStartDate, v))
}

// StartDateNEQ applies the NEQ predicate on the "start_date" field.
func StartDateNEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldStartDate, v))
}

// StartDateIn applies the In predicate on the "start_date" field.
func StartDateIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldStartDate, vs...))
}

// StartDateNotIn applies the NotIn predicate on the "start_date" field.
func StartDateNotIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldStartDate, vs...))
}

// StartDateGT applies the GT predicate on the "start_date" field.
func StartDateGT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldStartDate, v))
}

// StartDateGTE applies the GTE predicate on the "start_date" field.
func StartDateGTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldStartDate, v))
}

// StartDateLT applies the LT predicate on the "start_date" field.
func StartDateLT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldStartDate, v))
}

// StartDateLTE applies the LTE predicate on the "start_date" field.
func StartDateLTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldStartDate, v))
}

// StartDateIsNil applies the IsNil predicate on the "start_date" field.
func StartDateIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldStartDate))
}

// StartDateNotNil applies the NotNil predicate on the "start_date" field.
func StartDateNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldStartDate))
}

// DueDateEQ applies the EQ predicate on the "due_date" field.
func DueDateEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldDueDate, v))
}

// DueDateNEQ applies the NEQ predicate on the "due_date" field.
func DueDateNEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldDueDate, v))
}

// DueDateIn applies the In predicate on the "due_date" field.
func DueDateIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldDueDate, vs...))
}

// DueDateNotIn applies the NotIn predicate on the "due_date" field.
func DueDateNotIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldDueDate, vs...))
}

// DueDateGT applies the GT predicate on the "due_date" field.
func DueDateGT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldDueDate, v))
}

// DueDateGTE applies the GTE predicate on the "due_date" field.
func DueDateGTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldDueDate, v))
}

// DueDateLT applies the LT predicate on the "due_date" field.
func DueDateLT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldDueDate, v))
}

// DueDateLTE applies the LTE predicate on the "due_date" field.
func DueDateLTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldDueDate, v))
}

// DueDateIsNil applies the IsNil predicate on the "due_date" field.
func DueDateIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldDueDate))
}

// DueDateNotNil applies the NotNil predicate on the "due_date" field.
func DueDateNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldDueDate))
}

// ClosedAtEQ applies the EQ predicate on the "closed_at" field.
func ClosedAtEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldClosedAt, v))
}

// ClosedAtNEQ applies the NEQ predicate on the "closed_at" field.
func ClosedAtNEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldClosedAt, v))
}

// ClosedAtIn applies the In predicate on the "closed_at" field.
func ClosedAtIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldClosedAt, vs...))
}

// ClosedAtNotIn applies the NotIn predicate on the "closed_at" field.
func ClosedAtNotIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldClosedAt, vs...))
}

// ClosedAtGT applies the GT predicate on the "closed_at" field.
func ClosedAtGT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldClosedAt, v))
}

// ClosedAtGTE applies the GTE predicate on the "closed_at" field.
func ClosedAtGTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldClosedAt, v))
}

// ClosedAtLT applies the LT predicate on the "closed_at" field.
func ClosedAtLT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldClosedAt, v))
}

// ClosedAtLTE applies the LTE predicate on the "closed_at" field.
func ClosedAtLTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldClosedAt, v))
}

// ClosedAtIsNil applies the IsNil predicate on the "closed_at" field.
func ClosedAtIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldClosedAt))
}

// ClosedAtNotNil applies the NotNil predicate on the "closed_at" field.
func ClosedAtNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldClosedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldUpdatedAt, v))
}

// AcceptanceCriteriaEQ applies the EQ predicate on the "acceptance_criteria" field.
func AcceptanceCriteriaEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldAcceptanceCriteria, v))
}

// AcceptanceCriteriaNEQ applies the NEQ predicate on the "acceptance_criteria" field.
func AcceptanceCriteriaNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldAcceptanceCriteria, v))
}

// AcceptanceCriteriaIn applies the In predicate on the "acceptance_criteria" field.
func AcceptanceCriteriaIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldAcceptanceCriteria, vs...))
}

// AcceptanceCriteriaNotIn applies the NotIn predicate on the "acceptance_criteria" field.
func AcceptanceCriteriaNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldAcceptanceCriteria, vs...))
}

// AcceptanceCriteriaGT applies the GT predicate on the "acceptance_criteria" field.
func AcceptanceCriteriaGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldAcceptanceCriteria, v))
}

// AcceptanceCriteriaGTE applies the GTE predicate on the "acceptance_criteria" field.
func AcceptanceCriteriaGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldAcceptanceCriteria, v))
}

// AcceptanceCriteriaLT applies the LT predicate on the "acceptance_criteria" field.
func AcceptanceCriteriaLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldAcceptanceCriteria, v))
}

// AcceptanceCriteriaLTE applies the LTE predicate on the "acceptance_criteria" field.
func AcceptanceCriteriaLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldAcceptanceCriteria, v))
}

// AcceptanceCriteriaContains applies the Contains predicate on the "acceptance_criteria" field.
func AcceptanceCriteriaContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldAcceptanceCriteria, v))
}

// AcceptanceCriteriaHasPrefix applies the HasPrefix predicate on the "acceptance_criteria" field.
func AcceptanceCriteriaHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldAcceptanceCriteria, v))
}

// AcceptanceCriteriaHasSuffix applies the HasSuffix predicate on the "acceptance_criteria" field.
func AcceptanceCriteriaHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldAcceptanceCriteria, v))
}

// AcceptanceCriteriaIsNil applies the IsNil predicate on the "acceptance_criteria" field.
func AcceptanceCriteriaIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldAcceptanceCriteria))
}

// AcceptanceCriteriaNotNil applies the NotNil predicate on the "acceptance_criteria" field.
func AcceptanceCriteriaNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldAcceptanceCriteria))
}

// AcceptanceCriteriaEqualFold applies the EqualFold predicate on the "acceptance_criteria" field.
func AcceptanceCriteriaEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldAcceptanceCriteria, v))
}

// AcceptanceCriteriaContainsFold applies the ContainsFold predicate on the "acceptance_criteria" field.
func AcceptanceCriteriaContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldAcceptanceCriteria, v))
}

// RemoteDataIsNil applies the IsNil predicate on the "remote_data" field.
func RemoteDataIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldRemoteData))
}

// RemoteDataNotNil applies the NotNil predicate on the "remote_data" field.
func RemoteDataNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldRemoteData))
}

// LabelsIsNil applies the IsNil predicate on the "labels" field.
func LabelsIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldLabels))
}

// LabelsNotNil applies the NotNil predicate on the "labels" field.
func LabelsNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldLabels))
}

// RepoEQ applies the EQ predicate on the "repo" field.
func RepoEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldRepo, v))
}

// RepoNEQ applies the NEQ predicate on the "repo" field.
func RepoNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldRepo, v))
}

// RepoIn applies the In predicate on the "repo" field.
func RepoIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldRepo, vs...))
}

// RepoNotIn applies the NotIn predicate on the "repo" field.
func RepoNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldRepo, vs...))
}

// RepoGT applies the GT predicate on the "repo" field.
func RepoGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldRepo, v))
}

// RepoGTE applies the GTE predicate on the "repo" field.
func RepoGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldRepo, v))
}

// RepoLT applies the LT predicate on the "repo" field.
func RepoLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldRepo, v))
}

// RepoLTE applies the LTE predicate on the "repo" field.
func RepoLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldRepo, v))
}

// RepoContains applies the Contains predicate on the "repo" field.
func RepoContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldRepo, v))
}

// RepoHasPrefix applies the HasPrefix predicate on the "repo" field.
func RepoHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldRepo, v))
}

// RepoHasSuffix applies the HasSuffix predicate on the "repo" field.
func RepoHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldRepo, v))
}

// RepoIsNil applies the IsNil predicate on the "repo" field.
func RepoIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldRepo))
}

// RepoNotNil applies the NotNil predicate on the "repo" field.
func RepoNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldRepo))
}

// RepoEqualFold applies the EqualFold predicate on the "repo" field.
func RepoEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldRepo, v))
}

// RepoContainsFold applies the ContainsFold predicate on the "repo" field.
func RepoContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldRepo, v))
}

// BranchEQ applies the EQ predicate on the "branch" field.
func BranchEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldBranch, v))
}

// BranchNEQ applies the NEQ predicate on the "branch" field.
func BranchNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldBranch, v))
}

// BranchIn applies the In predicate on the "branch" field.
func BranchIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldBranch, vs...))
}

// BranchNotIn applies the NotIn predicate on the "branch" field.
func BranchNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldBranch, vs...))
}

// BranchGT applies the GT predicate on the "branch" field.
func BranchGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldBranch, v))
}

// BranchGTE applies the GTE predicate on the "branch" field.
func BranchGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldBranch, v))
}

// BranchLT applies the LT predicate on the "branch" field.
func BranchLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldBranch, v))
}

// BranchLTE applies the LTE predicate on the "branch" field.
func BranchLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldBranch, v))
}

// BranchContains applies the Contains predicate on the "branch" field.
func BranchContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldBranch, v))
}

// BranchHasPrefix applies the HasPrefix predicate on the "branch" field.
func BranchHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldBranch, v))
}

// BranchHasSuffix applies the HasSuffix predicate on the "branch" field.
func BranchHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldBranch, v))
}

// BranchIsNil applies the IsNil predicate on the "branch" field.
func BranchIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldBranch))
}

// BranchNotNil applies the NotNil predicate on the "branch" field.
func BranchNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldBranch))
}

// BranchEqualFold applies the EqualFold predicate on the "branch" field.
func BranchEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldBranch, v))
}

// BranchContainsFold applies the ContainsFold predicate on the "branch" field.
func BranchContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldBranch, v))
}

// CiStatusEQ applies the EQ predicate on the "ci_status" field.
func CiStatusEQ(v CiStatus) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCiStatus, v))
}

// CiStatusNEQ applies the NEQ predicate on the "ci_status" field.
func CiStatusNEQ(v CiStatus) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldCiStatus, v))
}

// CiStatusIn applies the In predicate on the "ci_status" field.
func CiStatusIn(vs ...CiStatus) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldCiStatus, vs...))
}

// CiStatusNotIn applies the NotIn predicate on the "ci_status" field.
func CiStatusNotIn(vs ...CiStatus) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldCiStatus, vs...))
}

// CiStatusIsNil applies the IsNil predicate on the "ci_status" field.
func CiStatusIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldCiStatus))
}

// CiStatusNotNil applies the NotNil predicate on the "ci_status" field.
func CiStatusNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldCiStatus))
}

// PullRequestsIsNil applies the IsNil predicate on the "pull_requests" field.
func PullRequestsIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldPullRequests))
}

// PullRequestsNotNil applies the NotNil predicate on the "pull_requests" field.
func PullRequestsNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldPullRequests))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldVersion, v))
}

// HasCollection applies the HasEdge predicate on the "collection" edge.
func HasCollection() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CollectionTable, CollectionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCollectionWith applies the HasEdge predicate on the "collection" edge with a given conditions (other predicates).
func HasCollectionWith(preds ...predicate.Collection) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newCollectionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasParent applies the HasEdge predicate on the "parent" edge.
func HasParent() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ParentTable, ParentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParentWith applies the HasEdge predicate on the "parent" edge with a given conditions (other predicates).
func HasParentWith(preds ...predicate.Task) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newParentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChildren applies the HasEdge predicate on the "children" edge.
func HasChildren() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ChildrenTable, ChildrenColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChildrenWith applies the HasEdge predicate on the "children" edge with a given conditions (other predicates).
func HasChildrenWith(preds ...predicate.Task) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newChildrenStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasComments applies the HasEdge predicate on the "comments" edge.
func HasComments() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CommentsTable, CommentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCommentsWith applies the HasEdge predicate on the "comments" edge with a given conditions (other predicates).
func HasCommentsWith(preds ...predicate.Comment) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newCommentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChanges applies the HasEdge predicate on the "changes" edge.
func HasChanges() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ChangesTable, ChangesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChangesWith applies the HasEdge predicate on the "changes" edge with a given conditions (other predicates).
func HasChangesWith(preds ...predicate.Change) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newChangesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSourceRelationships applies the HasEdge predicate on the "source_relationships" edge.
func HasSourceRelationships() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SourceRelationshipsTable, SourceRelationshipsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSourceRelationshipsWith applies the HasEdge predicate on the "source_relationships" edge with a given conditions (other predicates).
func HasSourceRelationshipsWith(preds ...predicate.Relationship) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newSourceRelationshipsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTargetRelationships applies the HasEdge predicate on the "target_relationships" edge.
func HasTargetRelationships() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TargetRelationshipsTable, TargetRelationshipsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTargetRelationshipsWith applies the HasEdge predicate on the "target_relationships" edge with a given conditions (other predicates).
func HasTargetRelationshipsWith(preds ...predicate.Relationship) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newTargetRelationshipsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Task) predicate.Task {
	return predicate.Task(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Task) predicate.Task {
	return predicate.Task(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Task) predicate.Task {
	return predicate.Task(sql.NotPredicates(p))
}
