import { setBasePath } from '@shoelace-style/shoelace/dist/utilities/base-path.js';

import '@shoelace-style/shoelace/dist/components/spinner/spinner.js';
import '@shoelace-style/shoelace/dist/components/radio-group/radio-group.js';
import '@shoelace-style/shoelace/dist/components/radio-button/radio-button.js';
import '@shoelace-style/shoelace/dist/components/select/select.js';
import '@shoelace-style/shoelace/dist/components/option/option.js';
import '@shoelace-style/shoelace/dist/components/button/button.js';
import '@shoelace-style/shoelace/dist/components/card/card.js';
import '@shoelace-style/shoelace/dist/components/badge/badge.js';
import '@shoelace-style/shoelace/dist/components/tag/tag.js';
import '@shoelace-style/shoelace/dist/components/avatar/avatar.js';
import '@shoelace-style/shoelace/dist/components/icon/icon.js';
import '@shoelace-style/shoelace/dist/components/icon-button/icon-button.js';
import '@shoelace-style/shoelace/dist/components/alert/alert.js';
import '@shoelace-style/shoelace/dist/components/divider/divider.js';
import '@shoelace-style/shoelace/dist/components/details/details.js';
import '@shoelace-style/shoelace/dist/components/dialog/dialog.js';
import '@shoelace-style/shoelace/dist/components/input/input.js';
import '@shoelace-style/shoelace/dist/components/textarea/textarea.js';
import '@shoelace-style/shoelace/dist/components/tooltip/tooltip.js';
import '@shoelace-style/shoelace/dist/components/tab-group/tab-group.js';
import '@shoelace-style/shoelace/dist/components/tab/tab.js';
import '@shoelace-style/shoelace/dist/components/tab-panel/tab-panel.js';
import '@shoelace-style/shoelace/dist/components/dropdown/dropdown.js';
import '@shoelace-style/shoelace/dist/components/menu/menu.js';
import '@shoelace-style/shoelace/dist/components/menu-item/menu-item.js';

import './styles/theme.css';
import './components/ft-connection-badge.js';
import './components/ft-toolbar.js';
import './components/ft-shortcut-overlay.js';
import './components/ft-import-collection-dialog.js';
import './components/ft-collection-list.js';
import './components/kanban/ft-task-card.js';
import './components/kanban/ft-kanban-column.js';
import './components/kanban/ft-add-task-dialog.js';
import './components/kanban/ft-kanban-view.js';
import './components/tree/ft-tree-node.js';
import './components/tree/ft-hierarchy-nav.js';
import './components/tree/ft-tree-view.js';
import './components/inspector/ft-inspector-header.js';
import './components/inspector/ft-inspector-meta.js';
import './components/inspector/ft-inspector-desc.js';
import './components/inspector/ft-inspector-relations.js';
import './components/inspector/ft-inspector-relationships.js';
import './components/inspector/ft-inspector-code.js';
import './components/inspector/ft-inspector-comments.js';
import './components/inspector/ft-inspector-changes.js';
import './components/inspector/ft-inspector.js';
import './components/ft-app.js';

setBasePath(import.meta.env.BASE_URL + 'shoelace');
